-- Auto-generated dari kanji_n5.json — jangan edit manual, edit file JSON lalu jalankan ulang script ini
DELETE FROM kanji WHERE level = 'N5';
INSERT INTO kanji (level, nomor, kanji, onyomi, kunyomi, romaji_onyomi, romaji_kunyomi, arti, contoh_kata, contoh_hiragana, contoh_arti) VALUES
  ('N5', '1', '日', 'ニチ、ジツ', 'ひ、-び、か', 'nichi, jitsu', 'hi, -bi, ka', 'Hari, matahari', '日曜日', 'にちようび', 'Hari Minggu'),
  ('N5', '2', '一', 'イチ、イツ', 'ひと-、ひと.つ', 'ichi, itsu', 'hito-, hitotsu', 'Satu', '一人', 'ひとり', 'Satu orang / sendirian'),
  ('N5', '3', '二', 'ニ', 'ふた、ふた.つ', 'ni', 'futa, futatsu', 'Dua', '二人', 'ふたり', 'Dua orang'),
  ('N5', '4', '三', 'サン', 'み、みっ.つ', 'san', 'mi, mittsu', 'Tiga', '三月', 'さんがつ', 'Bulan Maret'),
  ('N5', '5', '四', 'シ', 'よ、よ.つ、よっ.つ、よん', 'shi', 'yo, yotsu, yon', 'Empat', '四月', 'しがつ', 'Bulan April'),
  ('N5', '6', '五', 'ゴ', 'いつ、いつ.つ', 'go', 'itsu, itsutsu', 'Lima', '五月', 'ごがつ', 'Bulan Mei'),
  ('N5', '7', '六', 'ロク', 'む、む.つ、むっ.つ', 'roku', 'mu, mutsu, muttsu', 'Enam', '六月', 'ろくがつ', 'Bulan Juni'),
  ('N5', '8', '七', 'シチ', 'なな、なな.つ、なの', 'shichi', 'nana, nanatsu, nano', 'Tujuh', '七月', 'しちがつ', 'Bulan Juli'),
  ('N5', '9', '八', 'ハチ', 'や、や.つ、やっ.つ', 'hachi', 'ya, yatsu, yattsu', 'Delapan', '八月', 'はちがつ', 'Bulan Agustus'),
  ('N5', '10', '九', 'キュウ、ク', 'ここの、ここの.つ', 'kyuu, ku', 'kokono, kokonotsu', 'Sembilan', '九月', 'くがつ', 'Bulan September'),
  ('N5', '11', '十', 'ジュウ', 'とお、と', 'juu', 'too, to', 'Sepuluh', '十月', 'じゅうがつ', 'Bulan Oktober'),
  ('N5', '12', '人', 'ジン、ニン', 'ひと', 'jin, nin', 'hito', 'Orang', '日本人', 'にほんじん', 'Orang Jepang'),
  ('N5', '13', '大', 'ダイ、タイ', 'おお.きい', 'dai, tai', 'ookii', 'Besar', '大学', 'だいがく', 'Universitas'),
  ('N5', '14', '小', 'ショウ', 'ちい.さい、こ-、お-', 'shou', 'chiisai, ko-, o-', 'Kecil', '小学校', 'しょうがっこう', 'Sekolah dasar'),
  ('N5', '15', '中', 'チュウ', 'なか、うち', 'chuu', 'naka, uchi', 'Tengah, dalam', '中学校', 'ちゅうがっこう', 'Sekolah menengah pertama'),
  ('N5', '16', '山', 'サン', 'やま', 'san', 'yama', 'Gunung', '富士山', 'ふじさん', 'Gunung Fuji'),
  ('N5', '17', '川', 'セン', 'かわ', 'sen', 'kawa', 'Sungai', '小川', 'おがわ', 'Anak sungai'),
  ('N5', '18', '口', 'コウ', 'くち', 'kou', 'kuchi', 'Mulut', '入り口', 'いりぐち', 'Pintu masuk'),
  ('N5', '19', '目', 'モク', 'め', 'moku', 'me', 'Mata', '目的', 'もくてき', 'Tujuan'),
  ('N5', '20', '耳', 'ジ', 'みみ', 'ji', 'mimi', 'Telinga', '耳鼻科', 'じびか', 'Klinik THT'),
  ('N5', '21', '手', 'シュ', 'て', 'shu', 'te', 'Tangan', '上手', 'じょうず', 'Pandai, mahir'),
  ('N5', '22', '足', 'ソク', 'あし、た.りる', 'soku', 'ashi, tariru', 'Kaki, cukup', '足りる', 'たりる', 'Mencukupi'),
  ('N5', '23', '水', 'スイ', 'みず', 'sui', 'mizu', 'Air', '水曜日', 'すいようび', 'Hari Rabu'),
  ('N5', '24', '火', 'カ', 'ひ', 'ka', 'hi', 'Api', '火曜日', 'かようび', 'Hari Selasa'),
  ('N5', '25', '木', 'モク、ボク', 'き、こ-', 'moku, boku', 'ki, ko-', 'Pohon, kayu', '木曜日', 'もくようび', 'Hari Kamis'),
  ('N5', '26', '金', 'キン、コン', 'かね', 'kin, kon', 'kane', 'Emas, uang', '金曜日', 'きんようび', 'Hari Jumat'),
  ('N5', '27', '土', 'ド、ト', 'つち', 'do, to', 'tsuchi', 'Tanah', '土曜日', 'どようび', 'Hari Sabtu'),
  ('N5', '28', '子', 'シ', 'こ', 'shi', 'ko', 'Anak', '子供', 'こども', 'Anak-anak'),
  ('N5', '29', '女', 'ジョ', 'おんな', 'jo', 'onna', 'Perempuan', '女性', 'じょせい', 'Wanita'),
  ('N5', '30', '男', 'ダン、ナン', 'おとこ', 'dan, nan', 'otoko', 'Laki-laki', '男性', 'だんせい', 'Pria'),
  ('N5', '31', '年', 'ネン', 'とし', 'nen', 'toshi', 'Tahun', '今年', 'ことし', 'Tahun ini'),
  ('N5', '32', '月', 'ゲツ、ガツ', 'つき', 'getsu, gatsu', 'tsuki', 'Bulan', '月曜日', 'げつようび', 'Hari Senin'),
  ('N5', '33', '本', 'ホン', 'もと', 'hon', 'moto', 'Buku, asal', '日本', 'にほん', 'Jepang'),
  ('N5', '34', '語', 'ゴ', 'かた.る', 'go', 'kataru', 'Bahasa', '日本語', 'にほんご', 'Bahasa Jepang'),
  ('N5', '35', '学', 'ガク', 'まな.ぶ', 'gaku', 'manabu', 'Belajar, ilmu', '学生', 'がくせい', 'Siswa/mahasiswa'),
  ('N5', '36', '校', 'コウ', '-', 'kou', '-', 'Sekolah', '学校', 'がっこう', 'Sekolah'),
  ('N5', '37', '生', 'セイ', 'い.きる、う.まれる、なま', 'sei', 'ikiru, umareru, nama', 'Hidup, lahir', '先生', 'せんせい', 'Guru'),
  ('N5', '38', '先', 'セン', 'さき', 'sen', 'saki', 'Sebelumnya, ujung', '先週', 'せんしゅう', 'Minggu lalu'),
  ('N5', '39', '今', 'コン', 'いま', 'kon', 'ima', 'Sekarang', '今日', 'きょう', 'Hari ini'),
  ('N5', '40', '何', 'カ', 'なに、なん', 'ka', 'nani, nan', 'Apa', '何時', 'なんじ', 'Jam berapa'),
  ('N5', '41', '見', 'ケン', 'み.る、み.える', 'ken', 'miru, mieru', 'Melihat', '見物', 'けんぶつ', 'Melihat-lihat'),
  ('N5', '42', '行', 'コウ、ギョウ', 'い.く、おこな.う', 'kou, gyou', 'iku, okonau', 'Pergi, melaksanakan', '旅行', 'りょこう', 'Perjalanan/wisata'),
  ('N5', '43', '来', 'ライ', 'く.る、きた.る', 'rai', 'kuru, kitaru', 'Datang', '来週', 'らいしゅう', 'Minggu depan'),
  ('N5', '44', '食', 'ショク', 'た.べる、く.う', 'shoku', 'taberu, kuu', 'Makan', '食事', 'しょくじ', 'Makanan/santap'),
  ('N5', '45', '飲', 'イン', 'の.む', 'in', 'nomu', 'Minum', '飲み物', 'のみもの', 'Minuman'),
  ('N5', '46', '買', 'バイ', 'か.う', 'bai', 'kau', 'Membeli', '買い物', 'かいもの', 'Belanja'),
  ('N5', '47', '読', 'ドク', 'よ.む', 'doku', 'yomu', 'Membaca', '読書', 'どくしょ', 'Membaca buku'),
  ('N5', '48', '書', 'ショ', 'か.く', 'sho', 'kaku', 'Menulis', '辞書', 'じしょ', 'Kamus'),
  ('N5', '49', '話', 'ワ', 'はな.す、はなし', 'wa', 'hanasu, hanashi', 'Berbicara, cerita', '電話', 'でんわ', 'Telepon'),
  ('N5', '50', '聞', 'ブン', 'き.く、き.こえる', 'bun', 'kiku, kikoeru', 'Mendengar, bertanya', '新聞', 'しんぶん', 'Koran');
