-- Auto-generated dari kanji_n4.json — jangan edit manual, edit file JSON lalu jalankan ulang script ini
DELETE FROM kanji WHERE level = 'N4';
INSERT INTO kanji (level, nomor, kanji, onyomi, kunyomi, romaji_onyomi, romaji_kunyomi, arti, contoh_kata, contoh_hiragana, contoh_arti) VALUES
  ('N4', '1', '会', 'カイ', 'あ.う', 'kai', 'au', 'Bertemu, perkumpulan', '会社', 'かいしゃ', 'Perusahaan'),
  ('N4', '2', '同', 'ドウ', 'おな.じ', 'dou', 'onaji', 'Sama', '同じ', 'おなじ', 'Sama'),
  ('N4', '3', '事', 'ジ', 'こと', 'ji', 'koto', 'Hal, perkara', '仕事', 'しごと', 'Pekerjaan'),
  ('N4', '4', '自', 'ジ、シ', 'みずか.ら', 'ji, shi', 'mizukara', 'Diri sendiri', '自分', 'じぶん', 'Diri sendiri'),
  ('N4', '5', '社', 'シャ', 'やしろ', 'sha', 'yashiro', 'Perusahaan, kuil', '社会', 'しゃかい', 'Masyarakat'),
  ('N4', '6', '発', 'ハツ', 'た.つ', 'hatsu', 'tatsu', 'Berangkat, timbul', '出発', 'しゅっぱつ', 'Keberangkatan'),
  ('N4', '7', '者', 'シャ', 'もの', 'sha', 'mono', 'Orang (pelaku)', '医者', 'いしゃ', 'Dokter'),
  ('N4', '8', '地', 'チ、ジ', '-', 'chi, ji', '-', 'Tanah, bumi', '地図', 'ちず', 'Peta'),
  ('N4', '9', '業', 'ギョウ', 'わざ', 'gyou', 'waza', 'Usaha, pekerjaan', '授業', 'じゅぎょう', 'Pelajaran/kelas'),
  ('N4', '10', '方', 'ホウ', 'かた', 'hou', 'kata', 'Arah, cara', '使い方', 'つかいかた', 'Cara pemakaian'),
  ('N4', '11', '新', 'シン', 'あたら.しい', 'shin', 'atarashii', 'Baru', '新聞', 'しんぶん', 'Koran'),
  ('N4', '12', '場', 'ジョウ', 'ば', 'jou', 'ba', 'Tempat', '工場', 'こうじょう', 'Pabrik'),
  ('N4', '13', '員', 'イン', '-', 'in', '-', 'Anggota, pegawai', '会社員', 'かいしゃいん', 'Karyawan'),
  ('N4', '14', '立', 'リツ', 'た.つ、た.てる', 'ritsu', 'tatsu, tateru', 'Berdiri', '国立', 'こくりつ', 'Negeri (milik negara)'),
  ('N4', '15', '開', 'カイ', 'あ.く、あ.ける、ひら.く', 'kai', 'aku, akeru, hiraku', 'Membuka', '開始', 'かいし', 'Permulaan'),
  ('N4', '16', '手', 'シュ', 'て', 'shu', 'te', 'Tangan, pandai', '選手', 'せんしゅ', 'Atlet'),
  ('N4', '17', '力', 'リョク、リキ', 'ちから', 'ryoku, riki', 'chikara', 'Kekuatan', '努力', 'どりょく', 'Usaha keras'),
  ('N4', '18', '問', 'モン', 'と.う', 'mon', 'tou', 'Bertanya', '質問', 'しつもん', 'Pertanyaan'),
  ('N4', '19', '代', 'ダイ', 'か.わる、よ', 'dai', 'kawaru, yo', 'Generasi, pengganti', '時代', 'じだい', 'Zaman'),
  ('N4', '20', '明', 'メイ', 'あか.るい', 'mei', 'akarui', 'Terang, jelas', '説明', 'せつめい', 'Penjelasan'),
  ('N4', '21', '動', 'ドウ', 'うご.く', 'dou', 'ugoku', 'Bergerak', '運動', 'うんどう', 'Olahraga'),
  ('N4', '22', '京', 'キョウ', '-', 'kyou', '-', 'Ibu kota', '東京', 'とうきょう', 'Tokyo'),
  ('N4', '23', '目', 'モク', 'め', 'moku', 'me', 'Mata, ke- (urutan)', '二番目', 'にばんめ', 'Yang kedua'),
  ('N4', '24', '通', 'ツウ', 'とお.る、かよ.う', 'tsuu', 'tooru, kayou', 'Melewati, lalu lintas', '通学', 'つうがく', 'Pergi ke sekolah'),
  ('N4', '25', '度', 'ド', 'たび', 'do', 'tabi', 'Kali, derajat', '今度', 'こんど', 'Kali ini/lain kali'),
  ('N4', '26', '強', 'キョウ', 'つよ.い', 'kyou', 'tsuyoi', 'Kuat', '勉強', 'べんきょう', 'Belajar'),
  ('N4', '27', '公', 'コウ', 'おおやけ', 'kou', 'ooyake', 'Umum, publik', '公園', 'こうえん', 'Taman kota'),
  ('N4', '28', '持', 'ジ', 'も.つ', 'ji', 'motsu', 'Membawa, memiliki', '気持ち', 'きもち', 'Perasaan'),
  ('N4', '29', '野', 'ヤ', 'の', 'ya', 'no', 'Padang, liar', '野菜', 'やさい', 'Sayuran'),
  ('N4', '30', '海', 'カイ', 'うみ', 'kai', 'umi', 'Laut', '海外', 'かいがい', 'Luar negeri');
