-- Auto-generated dari kotoba_minna.json — jangan edit manual, edit file JSON lalu jalankan ulang script ini
DELETE FROM kotoba;
INSERT INTO kotoba (bab, nomor, kotoba, furigana, romaji, jenis_kata, arti, contoh_kalimat, contoh_kalimat_arti) VALUES
  ('1', '1', 'わたし', 'わたし', 'watashi', 'kata ganti', 'Saya', 'わたしは学生です。', 'Saya adalah mahasiswa.'),
  ('1', '2', 'あなた', 'あなた', 'anata', 'kata ganti', 'Anda, kamu', 'あなたは先生ですか。', 'Apakah Anda seorang guru?'),
  ('1', '3', 'あの人', 'あのひと', 'ano hito', 'kata ganti', 'Orang itu (di sana)', 'あの人は医者です。', 'Orang itu adalah dokter.'),
  ('1', '4', '先生', 'せんせい', 'sensei', 'kata benda', 'Guru, dosen', '山田さんは先生です。', 'Yamada adalah seorang guru.'),
  ('1', '5', '学生', 'がくせい', 'gakusei', 'kata benda', 'Siswa, mahasiswa', 'わたしは学生です。', 'Saya adalah mahasiswa.'),
  ('1', '6', '会社員', 'かいしゃいん', 'kaishain', 'kata benda', 'Karyawan perusahaan', '父は会社員です。', 'Ayah saya adalah karyawan perusahaan.'),
  ('1', '7', '医者', 'いしゃ', 'isha', 'kata benda', 'Dokter', 'あの人は医者です。', 'Orang itu adalah dokter.'),
  ('1', '8', '研究者', 'けんきゅうしゃ', 'kenkyuusha', 'kata benda', 'Peneliti', 'ワンさんは研究者です。', 'Wang adalah seorang peneliti.'),
  ('1', '9', 'エンジニア', 'エンジニア', 'enjinia', 'kata benda', 'Insinyur', 'わたしはエンジニアです。', 'Saya adalah seorang insinyur.'),
  ('1', '10', '大学', 'だいがく', 'daigaku', 'kata benda', 'Universitas', 'これは大学です。', 'Ini adalah universitas.'),
  ('1', '11', '病院', 'びょういん', 'byouin', 'kata benda', 'Rumah sakit', '病院はどこですか。', 'Di mana rumah sakit?'),
  ('1', '12', '電話番号', 'でんわばんごう', 'denwa bangou', 'kata benda', 'Nomor telepon', '電話番号は何番ですか。', 'Berapa nomor teleponnya?'),
  ('1', '13', '何歳', 'なんさい', 'nan-sai', 'kata tanya', 'Berapa umur', '何歳ですか。', 'Berapa umur Anda?'),
  ('1', '14', 'はい', 'はい', 'hai', 'kata seru', 'Ya', 'はい、そうです。', 'Ya, benar.'),
  ('1', '15', 'いいえ', 'いいえ', 'iie', 'kata seru', 'Tidak', 'いいえ、違います。', 'Tidak, itu salah.'),
  ('1', '16', '質問', 'しつもん', 'shitsumon', 'kata benda', 'Pertanyaan', '質問はありませんか。', 'Apakah ada pertanyaan?'),
  ('1', '17', 'じゃ', 'じゃ', 'jaa', 'kata sambung', 'Kalau begitu', 'じゃ、また明日。', 'Kalau begitu, sampai jumpa besok.'),
  ('1', '18', '違います', 'ちがいます', 'chigaimasu', 'kata kerja', 'Salah, berbeda', 'いいえ、違います。', 'Tidak, itu salah.'),
  ('2', '1', 'これ', 'これ', 'kore', 'kata tunjuk', 'Ini (dekat pembicara)', 'これは本です。', 'Ini adalah buku.'),
  ('2', '2', 'それ', 'それ', 'sore', 'kata tunjuk', 'Itu (dekat lawan bicara)', 'それは辞書です。', 'Itu adalah kamus.'),
  ('2', '3', 'あれ', 'あれ', 'are', 'kata tunjuk', 'Itu (jauh dari keduanya)', 'あれは私の傘です。', 'Itu adalah payung saya.'),
  ('2', '4', 'この', 'この', 'kono', 'kata sandang', 'Ini (+ kata benda)', 'この本は面白いです。', 'Buku ini menarik.'),
  ('2', '5', 'その', 'その', 'sono', 'kata sandang', 'Itu (+ kata benda, dekat lawan bicara)', 'その辞書をください。', 'Tolong berikan kamus itu.'),
  ('2', '6', 'あの', 'あの', 'ano', 'kata sandang', 'Itu (+ kata benda, jauh)', 'あの人は先生です。', 'Orang itu adalah guru.'),
  ('2', '7', '本', 'ほん', 'hon', 'kata benda', 'Buku', 'これは本です。', 'Ini adalah buku.'),
  ('2', '8', '辞書', 'じしょ', 'jisho', 'kata benda', 'Kamus', 'この辞書は新しいです。', 'Kamus ini baru.'),
  ('2', '9', '雑誌', 'ざっし', 'zasshi', 'kata benda', 'Majalah', '雑誌を読みます。', 'Membaca majalah.'),
  ('2', '10', '新聞', 'しんぶん', 'shinbun', 'kata benda', 'Koran', '新聞を読みます。', 'Membaca koran.'),
  ('2', '11', 'ノート', 'ノート', 'nooto', 'kata benda', 'Buku catatan', 'ノートに書きます。', 'Menulis di buku catatan.'),
  ('2', '12', '鉛筆', 'えんぴつ', 'enpitsu', 'kata benda', 'Pensil', '鉛筆で書きます。', 'Menulis dengan pensil.'),
  ('2', '13', 'かぎ', 'かぎ', 'kagi', 'kata benda', 'Kunci', 'かぎはどこですか。', 'Di mana kuncinya?'),
  ('2', '14', '時計', 'とけい', 'tokei', 'kata benda', 'Jam', 'その時計は高いです。', 'Jam itu mahal.'),
  ('2', '15', '傘', 'かさ', 'kasa', 'kata benda', 'Payung', 'あれは私の傘です。', 'Itu adalah payung saya.'),
  ('2', '16', 'かばん', 'かばん', 'kaban', 'kata benda', 'Tas', 'かばんの中に本があります。', 'Ada buku di dalam tas.'),
  ('2', '17', 'テレビ', 'テレビ', 'terebi', 'kata benda', 'Televisi', 'テレビを見ます。', 'Menonton televisi.'),
  ('2', '18', 'カメラ', 'カメラ', 'kamera', 'kata benda', 'Kamera', 'これは新しいカメラです。', 'Ini adalah kamera baru.'),
  ('2', '19', 'コンピューター', 'コンピューター', 'konpyuutaa', 'kata benda', 'Komputer', 'コンピューターを使います。', 'Menggunakan komputer.'),
  ('2', '20', '車', 'くるま', 'kuruma', 'kata benda', 'Mobil', 'あの車は私のです。', 'Mobil itu adalah milik saya.'),
  ('3', '1', 'ここ', 'ここ', 'koko', 'kata tunjuk tempat', 'Sini', 'ここは教室です。', 'Di sini adalah ruang kelas.'),
  ('3', '2', 'そこ', 'そこ', 'soko', 'kata tunjuk tempat', 'Situ', 'そこに事務所があります。', 'Di situ ada kantor.'),
  ('3', '3', 'あそこ', 'あそこ', 'asoko', 'kata tunjuk tempat', 'Sana', 'あそこはトイレです。', 'Di sana adalah toilet.'),
  ('3', '4', 'どこ', 'どこ', 'doko', 'kata tanya', 'Mana', 'トイレはどこですか。', 'Di mana toilet?'),
  ('3', '5', 'こちら', 'こちら', 'kochira', 'kata tunjuk arah', 'Sini (sopan)/arah ini', 'こちらへどうぞ。', 'Silakan ke sini.'),
  ('3', '6', '会社', 'かいしゃ', 'kaisha', 'kata benda', 'Perusahaan', '会社はあそこです。', 'Perusahaannya di sana.'),
  ('3', '7', 'うち', 'うち', 'uchi', 'kata benda', 'Rumah (sendiri)', 'うちに帰ります。', 'Pulang ke rumah.'),
  ('3', '8', '教室', 'きょうしつ', 'kyoushitsu', 'kata benda', 'Ruang kelas', 'ここは教室です。', 'Di sini adalah ruang kelas.'),
  ('3', '9', '食堂', 'しょくどう', 'shokudou', 'kata benda', 'Kantin', '食堂で食べます。', 'Makan di kantin.'),
  ('3', '10', '事務所', 'じむしょ', 'jimusho', 'kata benda', 'Kantor', '事務所はそこです。', 'Kantornya di situ.'),
  ('3', '11', '受付', 'うけつけ', 'uketsuke', 'kata benda', 'Resepsionis', '受付はどこですか。', 'Di mana resepsionis?'),
  ('3', '12', '部屋', 'へや', 'heya', 'kata benda', 'Kamar', 'これは私の部屋です。', 'Ini adalah kamar saya.'),
  ('3', '13', '階段', 'かいだん', 'kaidan', 'kata benda', 'Tangga', '階段を上がります。', 'Naik tangga.'),
  ('3', '14', 'エレベーター', 'エレベーター', 'erebeetaa', 'kata benda', 'Lift', 'エレベーターに乗ります。', 'Naik lift.'),
  ('3', '15', 'お手洗い', 'おてあらい', 'otearai', 'kata benda', 'Toilet (sopan)', 'お手洗いはあそこです。', 'Toiletnya di sana.');
