-- Auto-generated dari kanji_n4_lengkap_201.json — jangan edit manual, edit file JSON lalu jalankan ulang script ini
DELETE FROM kanji WHERE level = 'N4';
INSERT INTO kanji (level, nomor, kanji, onyomi, kunyomi, romaji_onyomi, romaji_kunyomi, arti, contoh_kata, contoh_hiragana, contoh_arti) VALUES
  ('N4', '1', '自', 'ジ、シ', 'みずか.ら', 'ji, shi', 'mizukara', 'Diri sendiri', '自分', 'じぶん', 'Diri sendiri'),
  ('N4', '2', '者', 'シャ', 'もの', 'sha', 'mono', 'Orang (pelaku)', '医者', 'いしゃ', 'Dokter'),
  ('N4', '3', '主', 'シュ', 'ぬし、おも', 'shu', 'nushi, omo', 'Tuan, utama', '主人', 'しゅじん', 'Suami/tuan rumah'),
  ('N4', '4', '家', 'カ', 'いえ、や、うち', 'ka', 'ie, ya, uchi', 'Rumah, keluarga', '家族', 'かぞく', 'Keluarga'),
  ('N4', '5', '私', 'シ', 'わたくし、わたし', 'shi', 'watakushi, watashi', 'Pribadi, saya', '私立', 'しりつ', 'Swasta'),
  ('N4', '6', '族', 'ゾク', '-', 'zoku', '-', 'Suku, keluarga', '民族', 'みんぞく', 'Suku bangsa'),
  ('N4', '7', '親', 'シン', 'おや、した.しい', 'shin', 'oya, shitashii', 'Orang tua, akrab', '親切', 'しんせつ', 'Ramah/baik hati'),
  ('N4', '8', '弟', 'テイ、ダイ、デ', 'おとうと', 'tei, dai, de', 'otouto', 'Adik laki-laki', '兄弟', 'きょうだい', 'Saudara kandung'),
  ('N4', '9', '兄', 'キョウ、ケイ', 'あに', 'kyou, kei', 'ani', 'Kakak laki-laki', 'お兄さん', 'おにいさん', 'Kakak laki-laki (panggilan)'),
  ('N4', '10', '妹', 'マイ', 'いもうと', 'mai', 'imouto', 'Adik perempuan', '姉妹', 'しまい', 'Kakak-adik perempuan'),
  ('N4', '11', '姉', 'シ', 'あね', 'shi', 'ane', 'Kakak perempuan', 'お姉さん', 'おねえさん', 'Kakak perempuan (panggilan)'),
  ('N4', '12', '手', 'シュ', 'て', 'shu', 'te', 'Tangan, pandai', '選手', 'せんしゅ', 'Atlet'),
  ('N4', '13', '目', 'モク、ボク', 'め', 'moku, boku', 'me', 'Mata, urutan ke-', '目的', 'もくてき', 'Tujuan'),
  ('N4', '14', '体', 'タイ', 'からだ', 'tai', 'karada', 'Badan, tubuh', '体育', 'たいいく', 'Pendidikan jasmani'),
  ('N4', '15', '心', 'シン', 'こころ', 'shin', 'kokoro', 'Hati, pikiran', '心配', 'しんぱい', 'Khawatir'),
  ('N4', '16', '口', 'コウ', 'くち', 'kou', 'kuchi', 'Mulut', '入り口', 'いりぐち', 'Pintu masuk'),
  ('N4', '17', '足', 'ソク', 'あし、た.りる', 'soku', 'ashi, tariru', 'Kaki, cukup', '足りる', 'たりる', 'Mencukupi'),
  ('N4', '18', '病', 'ビョウ', 'や.む', 'byou', 'yamu', 'Sakit', '病気', 'びょうき', 'Penyakit/sakit'),
  ('N4', '19', '医', 'イ', '-', 'i', '-', 'Dokter, pengobatan', '医院', 'いいん', 'Klinik'),
  ('N4', '20', '痛', 'ツウ', 'いた.い', 'tsuu', 'itai', 'Sakit', '痛い', 'いたい', 'Sakit'),
  ('N4', '21', '疲', 'ヒ', 'つか.れる', 'hi', 'tsukareru', 'Lelah', '疲れる', 'つかれる', 'Lelah'),
  ('N4', '22', '薬', 'ヤク', 'くすり', 'yaku', 'kusuri', 'Obat', '薬局', 'やっきょく', 'Apotek'),
  ('N4', '23', '代', 'ダイ', 'か.わり', 'dai', 'kawari', 'Generasi, pengganti', '時代', 'じだい', 'Zaman'),
  ('N4', '24', '朝', 'チョウ', 'あさ', 'chou', 'asa', 'Pagi', '朝食', 'ちょうしょく', 'Sarapan'),
  ('N4', '25', '早', 'ソウ、サッ', 'はや.い', 'sou, sa', 'hayai', 'Cepat, awal', '早朝', 'そうちょう', 'Pagi-pagi sekali'),
  ('N4', '26', '夜', 'ヤ', 'よ、よる', 'ya', 'yo, yoru', 'Malam', '夜中', 'よなか', 'Tengah malam'),
  ('N4', '27', '週', 'シュウ', '-', 'shuu', '-', 'Minggu (pekan)', '週間', 'しゅうかん', 'Kurun waktu seminggu'),
  ('N4', '28', '春', 'シュン', 'はる', 'shun', 'haru', 'Musim semi', '春休み', 'はるやすみ', 'Libur musim semi'),
  ('N4', '29', '秋', 'シュウ', 'あき', 'shuu', 'aki', 'Musim gugur', '秋田', 'あきた', 'Prefektur Akita'),
  ('N4', '30', '夏', 'カ、ゲ', 'なつ', 'ka, ge', 'natsu', 'Musim panas', '夏休み', 'なつやすみ', 'Libur musim panas'),
  ('N4', '31', '夕', '-', 'ゆう', '-', 'yuu', 'Sore/senja', '夕方', 'ゆうがた', 'Waktu sore'),
  ('N4', '32', '曜', 'ヨウ', '-', 'you', '-', 'Hari (dalam seminggu)', '曜日', 'ようび', 'Hari (dalam seminggu)'),
  ('N4', '33', '冬', 'トウ', 'ふゆ', 'tou', 'fuyu', 'Musim dingin', '冬休み', 'ふゆやすみ', 'Libur musim dingin'),
  ('N4', '34', '昼', 'チュウ', 'ひる', 'chuu', 'hiru', 'Siang', '昼食', 'ちゅうしょく', 'Makan siang'),
  ('N4', '35', '地', 'チ、ジ', '-', 'chi, ji', '-', 'Tanah, bumi', '地図', 'ちず', 'Peta'),
  ('N4', '36', '明', 'メイ、ミョウ', 'あか.るい', 'mei, myou', 'akarui', 'Terang, jelas', '説明', 'せつめい', 'Penjelasan'),
  ('N4', '37', '田', 'デン', 'た', 'den', 'ta', 'Sawah', '田舎', 'いなか', 'Pedesaan/kampung'),
  ('N4', '38', '野', 'ヤ', 'の', 'ya', 'no', 'Padang, liar', '野菜', 'やさい', 'Sayuran'),
  ('N4', '39', '海', 'カイ', 'うみ', 'kai', 'umi', 'Laut', '海外', 'かいがい', 'Luar negeri'),
  ('N4', '40', '空', 'クウ', 'そら、から、あ.く、す.く', 'kuu', 'sora, kara, aku, suku', 'Kosong, langit', '空港', 'くうこう', 'Bandara'),
  ('N4', '41', '風', 'フウ、フ', 'かぜ、かざ-', 'fuu, fu', 'kaze, kaza-', 'Angin, gaya', '風邪', 'かぜ', 'Masuk angin/flu'),
  ('N4', '42', '花', 'カ、ケ', 'はな', 'ka, ke', 'hana', 'Bunga', '花見', 'はなみ', 'Menikmati bunga sakura'),
  ('N4', '43', '鳥', 'チョウ', 'とり', 'chou', 'tori', 'Burung', '小鳥', 'ことり', 'Burung kecil'),
  ('N4', '44', '牛', 'ギュウ', 'うし', 'gyuu', 'ushi', 'Sapi', '牛乳', 'ぎゅうにゅう', 'Susu sapi'),
  ('N4', '45', '魚', 'ギョ', 'うお、さかな', 'gyo', 'uo, sakana', 'Ikan', '金魚', 'きんぎょ', 'Ikan mas koki'),
  ('N4', '46', '犬', 'ケン', 'いぬ', 'ken', 'inu', 'Anjing', '子犬', 'こいぬ', 'Anak anjing'),
  ('N4', '47', '暗', 'アン', 'くら.い', 'an', 'kurai', 'Gelap', '暗い', 'くらい', 'Gelap'),
  ('N4', '48', '太', 'タイ、タ', 'ふと.る、ふと.い', 'tai, ta', 'futoru, futoi', 'Gemuk, tebal', '太る', 'ふとる', 'Menjadi gemuk'),
  ('N4', '49', '細', 'サイ', 'ほそ.い、こま.かい', 'sai', 'hosoi, komakai', 'Tipis, detail', '細かい', 'こまかい', 'Detail/kecil'),
  ('N4', '50', '冷', 'レイ', 'つめ.たい、ひ.える', 'rei', 'tsumetai, hieru', 'Dingin (benda)', '冷たい', 'つめたい', 'Dingin'),
  ('N4', '51', '熱', 'ネツ', 'あつ.い', 'netsu', 'atsui', 'Panas (benda/demam)', '熱い', 'あつい', 'Panas'),
  ('N4', '52', '暖', 'ダン', 'あたた.かい', 'dan', 'atatakai', 'Hangat', '暖かい', 'あたたかい', 'Hangat'),
  ('N4', '53', '涼', 'リョウ', 'すず.しい', 'ryou', 'suzushii', 'Sejuk', '涼しい', 'すずしい', 'Sejuk'),
  ('N4', '54', '社', 'シャ', 'やしろ', 'sha', 'yashiro', 'Perusahaan, kuil', '社会', 'しゃかい', 'Masyarakat'),
  ('N4', '55', '場', 'ジョウ', 'ば', 'jou', 'ba', 'Tempat', '工場', 'こうじょう', 'Pabrik'),
  ('N4', '56', '京', 'キョウ、ケイ、キン', 'みやこ', 'kyou, kei, kin', 'miyako', 'Ibu kota', '東京', 'とうきょう', 'Tokyo'),
  ('N4', '57', '院', 'イン', '-', 'in', '-', 'Institusi, rumah sakit', '病院', 'びょういん', 'Rumah sakit'),
  ('N4', '58', '町', 'チョウ', 'まち', 'chou', 'machi', 'Kota kecil, kelurahan', '町内', 'ちょうない', 'Lingkungan setempat'),
  ('N4', '59', '建', 'ケン、コン', 'た.てる', 'ken, kon', 'tateru', 'Membangun', '建物', 'たてもの', 'Bangunan'),
  ('N4', '60', '店', 'テン', 'みせ', 'ten', 'mise', 'Toko', '店員', 'てんいん', 'Pegawai toko'),
  ('N4', '61', '室', 'シツ', 'むろ', 'shitsu', 'muro', 'Kamar, ruangan', '地下室', 'ちかしつ', 'Ruang bawah tanah'),
  ('N4', '62', '館', 'カン', 'やかた', 'kan', 'yakata', 'Gedung, aula', '図書館', 'としょかん', 'Perpustakaan'),
  ('N4', '63', '屋', 'オク', 'や', 'oku', 'ya', 'Atap, toko', '部屋', 'へや', 'Kamar'),
  ('N4', '64', '駅', 'エキ', '-', 'eki', '-', 'Stasiun', '駅員', 'えきいん', 'Petugas stasiun'),
  ('N4', '65', '堂', 'ドウ', '-', 'dou', '-', 'Aula, ruang publik', '食堂', 'しょくどう', 'Kantin/rumah makan'),
  ('N4', '66', '局', 'キョク', '-', 'kyoku', '-', 'Biro, departemen', '郵便局', 'ゆうびんきょく', 'Kantor pos'),
  ('N4', '67', '発', 'ハツ、ホツ', '-', 'hatsu, hotsu', '-', 'Berangkat, timbul', '出発', 'しゅっぱつ', 'Keberangkatan'),
  ('N4', '68', '方', 'ホウ', 'かた', 'hou', 'kata', 'Arah, cara, orang', '使い方', 'つかいかた', 'Cara pemakaian'),
  ('N4', '69', '立', 'リツ', 'た.つ', 'ritsu', 'tatsu', 'Berdiri', '国立', 'こくりつ', 'Negeri (milik negara)'),
  ('N4', '70', '動', 'ドウ', 'うご.く', 'dou', 'ugoku', 'Bergerak', '運動', 'うんどう', 'Olahraga'),
  ('N4', '71', '通', 'ツウ', 'とお.る、かよ.う', 'tsuu', 'tooru, kayou', 'Melewati, lalu lintas', '交通', 'こうつう', 'Lalu lintas'),
  ('N4', '72', '道', 'ドウ', 'みち', 'dou', 'michi', 'Jalan', '道路', 'どうろ', 'Jalan raya'),
  ('N4', '73', '急', 'キュウ', 'いそ.ぐ', 'kyuu', 'isogu', 'Buru-buru, mendadak', '急行', 'きゅうこう', 'Kereta cepat'),
  ('N4', '74', '止', 'シ', 'と.まる、とど.まる、や.める', 'shi', 'tomaru, todomaru, yameru', 'Berhenti', '中止', 'ちゅうし', 'Pembatalan'),
  ('N4', '75', '送', 'ソウ', 'おく.る', 'sou', 'okuru', 'Mengirim, mengantar', '送料', 'そうりょう', 'Biaya kirim'),
  ('N4', '76', '転', 'テン', 'ころ.がる', 'ten', 'korogaru', 'Berputar, berpindah', '自転車', 'じてんしゃ', 'Sepeda'),
  ('N4', '77', '起', 'キ', 'お.きる、おこ.す', 'ki', 'okiru, okosu', 'Bangun, terjadi', '起床', 'きしょう', 'Bangun tidur'),
  ('N4', '78', '着', 'チャク', 'き.る、つ.く', 'chaku', 'kiru, tsuku', 'Sampai, memakai', '到着', 'とうちゃく', 'Kedatangan/tiba'),
  ('N4', '79', '帰', 'キ', 'かえ.る、かえ.す', 'ki', 'kaeru, kaesu', 'Pulang', '帰国', 'きこく', 'Pulang ke negara asal'),
  ('N4', '80', '歩', 'ホ、ブ', 'ある.く、あゆ.む', 'ho, bu', 'aruku, ayumu', 'Berjalan', '散歩', 'さんぽ', 'Jalan-jalan'),
  ('N4', '81', '走', 'ソウ', 'はし.る', 'sou', 'hashiru', 'Berlari', '走る', 'はしる', 'Berlari'),
  ('N4', '82', '乗', 'ジョウ', 'の.る', 'jou', 'noru', 'Naik (kendaraan)', '乗車', 'じょうしゃ', 'Naik kereta/bus'),
  ('N4', '83', '降', 'コウ', 'ふ.る、お.りる', 'kou', 'furu, oriru', 'Turun', '降りる', 'おりる', 'Turun kendaraan'),
  ('N4', '84', '泳', 'エイ', 'およ.ぐ', 'ei', 'oyogu', 'Berenang', '水泳', 'すいえい', 'Renang'),
  ('N4', '85', '飛', 'ヒ', 'と.ぶ', 'hi', 'tobu', 'Terbang', '飛行機', 'ひこうき', 'Pesawat terbang'),
  ('N4', '86', '渡', 'ト', 'わた.る、わた.す', 'to', 'wataru, watasu', 'Menyeberang', '渡る', 'わたる', 'Menyeberang'),
  ('N4', '87', '物', 'ブツ、モツ', 'もの', 'butsu, motsu', 'mono', 'Barang, benda', '荷物', 'にもつ', 'Barang bawaan'),
  ('N4', '88', '品', 'ヒン', 'しな', 'hin', 'shina', 'Barang, mutu', '商品', 'しょうひん', 'Barang dagangan'),
  ('N4', '89', '紙', 'シ', 'かみ', 'shi', 'kami', 'Kertas', '手紙', 'てがみ', 'Surat'),
  ('N4', '90', '洋', 'ヨウ', '-', 'you', '-', 'Laut, gaya barat', '洋服', 'ようふく', 'Baju bergaya barat'),
  ('N4', '91', '服', 'フク', '-', 'fuku', '-', 'Pakaian', '服装', 'ふくそう', 'Cara berpakaian'),
  ('N4', '92', '飲', 'イン', 'の.む', 'in', 'nomu', 'Minum', '飲み物', 'のみもの', 'Minuman'),
  ('N4', '93', '肉', 'ニク', '-', 'niku', '-', 'Daging', '牛肉', 'ぎゅうにく', 'Daging sapi'),
  ('N4', '94', '飯', 'ハン', 'めし', 'han', 'meshi', 'Nasi, makanan', 'ご飯', 'ごはん', 'Nasi/makanan'),
  ('N4', '95', '茶', 'チャ、サ', '-', 'cha, sa', '-', 'Teh', 'お茶', 'おちゃ', 'Teh'),
  ('N4', '96', '問', 'モン', 'と.う', 'mon', 'tou', 'Bertanya', '質問', 'しつもん', 'Pertanyaan'),
  ('N4', '97', '言', 'ゲン、ゴン', 'い.う、こと', 'gen, gon', 'iu, koto', 'Berkata, kata', '言葉', 'ことば', 'Kata, bahasa'),
  ('N4', '98', '理', 'リ', '-', 'ri', '-', 'Logika, susunan', '料理', 'りょうり', 'Masakan'),
  ('N4', '99', '題', 'ダイ', '-', 'dai', '-', 'Judul, topik', '問題', 'もんだい', 'Masalah/soal'),
  ('N4', '100', '意', 'イ', '-', 'i', '-', 'Pikiran, makna', '意味', 'いみ', 'Arti/makna'),
  ('N4', '101', '教', 'キョウ', 'おし.える、おそ.わる', 'kyou', 'oshieru, osowaru', 'Mengajar', '教室', 'きょうしつ', 'Ruang kelas'),
  ('N4', '102', '文', 'ブン、モン', 'ふみ', 'bun, mon', 'fumi', 'Kalimat, tulisan', '文化', 'ぶんか', 'Kebudayaan'),
  ('N4', '103', '考', 'コウ', 'かんが.える', 'kou', 'kangaeru', 'Berpikir, mempertimbangkan', '考え方', 'かんがえかた', 'Cara berpikir'),
  ('N4', '104', '画', 'ガ、カク', '-', 'ga, kaku', '-', 'Gambar, lukisan', '映画', 'えいが', 'Film'),
  ('N4', '105', '知', 'チ', 'し.る', 'chi', 'shiru', 'Mengetahui', '知識', 'ちしき', 'Pengetahuan'),
  ('N4', '106', '研', 'ケン', 'と.ぐ', 'ken', 'togu', 'Mengasah, meneliti', '研修', 'けんしゅう', 'Pelatihan'),
  ('N4', '107', '究', 'キュウ', '-', 'kyuu', '-', 'Meneliti', '研究', 'けんきゅう', 'Penelitian'),
  ('N4', '108', '試', 'シ', 'こころ.みる、ため.す', 'shi', 'kokoromiru, tamesu', 'Mencoba, ujian', '試験', 'しけん', 'Ujian'),
  ('N4', '109', '験', 'ケン', '-', 'ken', '-', 'Verifikasi, uji', '経験', 'けいけん', 'Pengalaman'),
  ('N4', '110', '英', 'エイ', '-', 'ei', '-', 'Inggris, unggul', '英語', 'えいご', 'Bahasa Inggris'),
  ('N4', '111', '写', 'シャ', 'うつ.る', 'sha', 'utsuru', 'Menyalin, memotret', '写生', 'しゃせい', 'Melukis dari alam'),
  ('N4', '112', '字', 'ジ', '-', 'ji', '-', 'Huruf, karakter', '漢字', 'かんじ', 'Kanji'),
  ('N4', '113', '答', 'トウ', 'こた.える', 'tou', 'kotaeru', 'Menjawab', '答え', 'こたえ', 'Jawaban'),
  ('N4', '114', '音', 'オン', 'おと、ね', 'on', 'oto, ne', 'Suara, bunyi', '音声', 'おんせい', 'Suara/audio'),
  ('N4', '115', '注', 'チュウ', 'そそ.ぐ、さ.す', 'chuu', 'sosogu, sasu', 'Menuang, memperhatikan', '注意', 'ちゅうい', 'Perhatian/hati-hati'),
  ('N4', '116', '歌', 'カ', 'うた、うた.う', 'ka', 'uta, utau', 'Lagu, bernyanyi', '歌手', 'かしゅ', 'Penyanyi'),
  ('N4', '117', '図', 'ズ、ト', 'はか.る', 'zu, to', 'hakaru', 'Peta, gambar', '地図', 'ちず', 'Peta'),
  ('N4', '118', '習', 'シュウ', 'なら.う', 'shuu', 'narau', 'Belajar/berlatih', '習慣', 'しゅうかん', 'Kebiasaan'),
  ('N4', '119', '漢', 'カン', '-', 'kan', '-', 'Tiongkok/China', '漢方', 'かんぽう', 'Obat tradisional Tiongkok'),
  ('N4', '120', '育', 'イク', 'そだ.てる', 'iku', 'sodateru', 'Membesarkan', '教育', 'きょういく', 'Pendidikan'),
  ('N4', '121', '会', 'カイ', 'あ.う', 'kai', 'au', 'Bertemu, perkumpulan', '会社', 'かいしゃ', 'Perusahaan'),
  ('N4', '122', '同', 'ドウ', 'おな.じ', 'dou', 'onaji', 'Sama', '同じ', 'おなじ', 'Sama'),
  ('N4', '123', '事', 'ジ', 'こと', 'ji', 'koto', 'Hal, perkara', '仕事', 'しごと', 'Pekerjaan'),
  ('N4', '124', '業', 'ギョウ', 'わざ', 'gyou', 'waza', 'Usaha, pekerjaan', '授業', 'じゅぎょう', 'Pelajaran/kelas'),
  ('N4', '125', '員', 'イン', '-', 'in', '-', 'Anggota, pegawai', '会社員', 'かいしゃいん', 'Karyawan'),
  ('N4', '126', '作', 'サク、サ', 'つく.る', 'saku, sa', 'tsukuru', 'Membuat', '作文', 'さくぶん', 'Karangan'),
  ('N4', '127', '用', 'ヨウ', 'もち.いる', 'you', 'mochiiru', 'Menggunakan', '使用', 'しよう', 'Penggunaan'),
  ('N4', '128', '度', 'ド、タク', 'たび', 'do, taku', 'tabi', 'Kali, derajat', '今度', 'こんど', 'Kali ini/lain kali'),
  ('N4', '129', '強', 'キョウ、ゴウ', 'つよ.い', 'kyou, gou', 'tsuyoi', 'Kuat', '勉強', 'べんきょう', 'Belajar'),
  ('N4', '130', '公', 'コウ', '-', 'kou', '-', 'Umum, publik', '公園', 'こうえん', 'Taman kota'),
  ('N4', '131', '持', 'ジ', 'も.つ', 'ji', 'motsu', 'Membawa, memiliki', '気持ち', 'きもち', 'Perasaan'),
  ('N4', '132', '売', 'バイ', 'う.る', 'bai', 'uru', 'Menjual', '売店', 'ばいてん', 'Kios/toko kecil'),
  ('N4', '133', '使', 'シ', 'つか.う', 'shi', 'tsukau', 'Menggunakan', '大使', 'たいし', 'Duta besar'),
  ('N4', '134', '計', 'ケイ', 'はか.る', 'kei', 'hakaru', 'Rencana, mengukur', '時計', 'とけい', 'Jam (arloji)'),
  ('N4', '135', '料', 'リョウ', '-', 'ryou', '-', 'Biaya, bahan', '料金', 'りょうきん', 'Biaya/tarif'),
  ('N4', '136', '工', 'コウ、ク、グ', '-', 'kou, ku, gu', '-', 'Kerajinan, konstruksi', '工事', 'こうじ', 'Konstruksi/pembangunan'),
  ('N4', '137', '銀', 'ギン', '-', 'gin', '-', 'Perak', '銀行', 'ぎんこう', 'Bank'),
  ('N4', '138', '仕', 'シ', '-', 'shi', '-', 'Melayani, bekerja', '仕方', 'しかた', 'Cara melakukan'),
  ('N4', '139', '買', 'バイ', 'か.う', 'bai', 'kau', 'Membeli', '買い物', 'かいもの', 'Belanja'),
  ('N4', '140', '借', 'シャク', 'か.りる', 'shaku', 'kariru', 'Meminjam', '借金', 'しゃっきん', 'Utang'),
  ('N4', '141', '貸', 'タイ', 'か.す、かし', 'tai', 'kasu, kashi', 'Meminjamkan', '貸す', 'かす', 'Meminjamkan'),
  ('N4', '142', '勉', 'ベン', 'つと.める', 'ben', 'tsutomeru', 'Berusaha, rajin', '勤勉', 'きんべん', 'Rajin'),
  ('N4', '143', '忙', 'ボウ', 'いそが.しい', 'bou', 'isogashii', 'Sibuk', '忙しい', 'いそがしい', 'Sibuk'),
  ('N4', '144', '働', 'ドウ', 'はたら.く', 'dou', 'hataraku', 'Bekerja', '働く', 'はたらく', 'Bekerja'),
  ('N4', '145', '産', 'サン', 'う.む', 'san', 'umu', 'Melahirkan, produksi', '生産', 'せいさん', 'Produksi'),
  ('N4', '146', '新', 'シン', 'あたら.しい、あら.た', 'shin', 'atarashii, arata', 'Baru', '新聞', 'しんぶん', 'Koran'),
  ('N4', '147', '開', 'カイ', 'ひら.く、あ.ける', 'kai', 'hiraku, akeru', 'Membuka', '開始', 'かいし', 'Permulaan'),
  ('N4', '148', '力', 'リョク、リキ', 'ちから', 'ryoku, riki', 'chikara', 'Kekuatan', '努力', 'どりょく', 'Usaha keras'),
  ('N4', '149', '以', 'イ', 'も.って', 'i', 'motte', 'Dengan, berdasarkan', '以上', 'いじょう', 'Lebih dari, di atas'),
  ('N4', '150', '世', 'セイ、セ', 'よ', 'sei, se', 'yo', 'Dunia, generasi', '世界', 'せかい', 'Dunia'),
  ('N4', '151', '多', 'タ', 'おお.い', 'ta', 'ooi', 'Banyak', '多分', 'たぶん', 'Mungkin/barangkali'),
  ('N4', '152', '正', 'セイ、ショウ', 'ただ.しい、まさ.に', 'sei, shou', 'tadashii, masani', 'Benar', '正月', 'しょうがつ', 'Tahun baru (Jepang)'),
  ('N4', '153', '安', 'アン', 'やす.い', 'an', 'yasui', 'Aman, murah', '安心', 'あんしん', 'Merasa tenang'),
  ('N4', '154', '界', 'カイ', '-', 'kai', '-', 'Dunia, batas', '業界', 'ぎょうかい', 'Dunia industri'),
  ('N4', '155', '重', 'ジュウ、チョウ', 'おも.い、かさ.ねる', 'juu, chou', 'omoi, kasaneru', 'Berat, penting', '重要', 'じゅうよう', 'Penting'),
  ('N4', '156', '近', 'キン', 'ちか.い', 'kin', 'chikai', 'Dekat', '近所', 'きんじょ', 'Sekitar/tetangga'),
  ('N4', '157', '集', 'シュウ', 'あつ.める', 'shuu', 'atsumeru', 'Mengumpulkan', '集合', 'しゅうごう', 'Berkumpul'),
  ('N4', '158', '別', 'ベツ', 'わか.れる、わ.ける', 'betsu', 'wakareru, wakeru', 'Berpisah, terpisah', '別々', 'べつべつ', 'Terpisah/sendiri-sendiri'),
  ('N4', '159', '死', 'シ', 'し.ぬ', 'shi', 'shinu', 'Mati', '死亡', 'しぼう', 'Kematian'),
  ('N4', '160', '特', 'トク', '-', 'toku', '-', 'Khusus', '特別', 'とくべつ', 'Istimewa/khusus'),
  ('N4', '161', '台', 'ダイ、タイ', '-', 'dai, tai', '-', 'Alas, penghitung mesin/kendaraan', '台風', 'たいふう', 'Topan/badai'),
  ('N4', '162', '広', 'コウ', 'ひろ.い', 'kou', 'hiroi', 'Luas', '広告', 'こうこく', 'Iklan'),
  ('N4', '163', '無', 'ム、ブ', 'な.い', 'mu, bu', 'nai', 'Tidak ada', '無料', 'むりょう', 'Gratis'),
  ('N4', '164', '真', 'シン', 'ま、まこと', 'shin', 'ma, makoto', 'Sungguh, asli', '写真', 'しゃしん', 'Foto'),
  ('N4', '165', '有', 'ユウ、ウ', 'あ.る', 'yuu, u', 'aru', 'Memiliki, ada', '有名', 'ゆうめい', 'Terkenal'),
  ('N4', '166', '少', 'ショウ', 'すく.ない、すこ.し', 'shou', 'sukunai, sukoshi', 'Sedikit', '少し', 'すこし', 'Sedikit'),
  ('N4', '167', '楽', 'ガク、ラク', 'たの.しい', 'gaku, raku', 'tanoshii', 'Musik, senang', '音楽', 'おんがく', 'Musik'),
  ('N4', '168', '質', 'シツ、シチ', 'たち、ただ.す', 'shitsu, shichi', 'tachi, tadasu', 'Kualitas, sifat', '品質', 'ひんしつ', 'Kualitas barang'),
  ('N4', '169', '待', 'タイ', 'ま.つ', 'tai', 'matsu', 'Menunggu', '期待', 'きたい', 'Harapan'),
  ('N4', '170', '映', 'エイ', 'うつ.る、は.える', 'ei', 'utsuru, haeru', 'Memantul, tercermin', '映像', 'えいぞう', 'Citra/gambar video'),
  ('N4', '171', '去', 'キョ、コ', 'さ.る', 'kyo, ko', 'saru', 'Berlalu, pergi', '過去', 'かこ', 'Masa lalu'),
  ('N4', '172', '味', 'ミ', 'あじ', 'mi', 'aji', 'Rasa', '興味', 'きょうみ', 'Minat'),
  ('N4', '173', '古', 'コ', 'ふる.い', 'ko', 'furui', 'Lama, kuno', '中古', 'ちゅうこ', 'Barang bekas'),
  ('N4', '174', '悪', 'アク', 'わる.い', 'aku', 'warui', 'Buruk, jahat', '悪い', 'わるい', 'Buruk/jahat'),
  ('N4', '175', '黒', 'コク', 'くろ', 'koku', 'kuro', 'Hitam', '黒い', 'くろい', 'Hitam'),
  ('N4', '176', '赤', 'セキ、シャク', 'あか.い', 'seki, shaku', 'akai', 'Merah', '赤い', 'あかい', 'Merah'),
  ('N4', '177', '青', 'セイ、ショウ', 'あお.い', 'sei, shou', 'aoi', 'Biru', '青い', 'あおい', 'Biru'),
  ('N4', '178', '色', 'ショク、シキ', 'いろ', 'shoku, shiki', 'iro', 'Warna', '色々', 'いろいろ', 'Bermacam-macam'),
  ('N4', '179', '洗', 'セン', 'あら.う', 'sen', 'arau', 'Mencuci', '洗濯', 'せんたく', 'Mencuci pakaian'),
  ('N4', '180', '閉', 'ヘイ', 'し.める、と.じる', 'hei', 'shimeru, tojiru', 'Menutup', '閉める', 'しめる', 'Menutup'),
  ('N4', '181', '引', 'イン', 'ひ.く', 'in', 'hiku', 'Menarik', '引き出し', 'ひきだし', 'Laci'),
  ('N4', '182', '押', 'オウ', 'お.す', 'ou', 'osu', 'Menekan', '押す', 'おす', 'Menekan'),
  ('N4', '183', '短', 'タン', 'みじか.い', 'tan', 'mijikai', 'Pendek', '短い', 'みじかい', 'Pendek'),
  ('N4', '184', '低', 'テイ', 'ひく.い', 'tei', 'hikui', 'Rendah', '低い', 'ひくい', 'Rendah'),
  ('N4', '185', '弱', 'ジャク', 'よわ.い', 'jaku', 'yowai', 'Lemah', '弱い', 'よわい', 'Lemah'),
  ('N4', '186', '軽', 'ケイ', 'かる.い', 'kei', 'karui', 'Ringan', '軽い', 'かるい', 'Ringan'),
  ('N4', '187', '静', 'セイ', 'しず.か', 'sei', 'shizuka', 'Tenang', '静か', 'しずか', 'Tenang'),
  ('N4', '188', '悲', 'ヒ', 'かな.しい', 'hi', 'kanashii', 'Sedih', '悲しい', 'かなしい', 'Sedih'),
  ('N4', '189', '怒', 'ド', 'おこ.る', 'do', 'okoru', 'Marah', '怒る', 'おこる', 'Marah'),
  ('N4', '190', '泣', 'キュウ', 'な.く', 'kyuu', 'naku', 'Menangis', '泣く', 'なく', 'Menangis'),
  ('N4', '191', '笑', 'ショウ', 'わら.う', 'shou', 'warau', 'Tertawa', '笑う', 'わらう', 'Tertawa'),
  ('N4', '192', '寝', 'シン', 'ね.る', 'shin', 'neru', 'Tidur', '寝る', 'ねる', 'Tidur'),
  ('N4', '193', '不', 'フ、ブ', '-', 'fu, bu', '-', 'Tidak, bukan', '不安', 'ふあん', 'Cemas'),
  ('N4', '194', '思', 'シ', 'おも.う', 'shi', 'omou', 'Berpikir', '思い出', 'おもいで', 'Kenangan'),
  ('N4', '195', '元', 'ゲン、ガン', 'もと', 'gen, gan', 'moto', 'Asal, awal', '元気', 'げんき', 'Sehat/semangat'),
  ('N4', '196', '始', 'シ', 'はじ.める', 'shi', 'hajimeru', 'Memulai', '始発', 'しはつ', 'Keberangkatan pertama'),
  ('N4', '197', '運', 'ウン', 'はこ.ぶ', 'un', 'hakobu', 'Membawa, nasib', '運転', 'うんてん', 'Mengemudi'),
  ('N4', '198', '終', 'シュウ', 'お.わる', 'shuu', 'owaru', 'Berakhir', '終電', 'しゅうでん', 'Kereta terakhir'),
  ('N4', '199', '住', 'ジュウ、チュウ', 'す.む', 'juu, chuu', 'sumu', 'Tinggal, berdiam', '住所', 'じゅうしょ', 'Alamat'),
  ('N4', '200', '切', 'セツ、サイ', 'き.る', 'setsu, sai', 'kiru', 'Memotong', '切符', 'きっぷ', 'Tiket'),
  ('N4', '201', '旅', 'リョ', 'たび', 'ryo', 'tabi', 'Perjalanan', '旅行', 'りょこう', 'Perjalanan/wisata');