-- Auto-generated dari kanji_n5.json — jangan edit manual, edit file JSON lalu jalankan ulang script ini
DELETE FROM kanji WHERE level = 'N5';
INSERT INTO kanji (level, nomor, kanji, onyomi, kunyomi, romaji_onyomi, romaji_kunyomi, arti, contoh_kata, contoh_hiragana, contoh_arti) VALUES
  ('N5', '1', '日', 'ニチ、ジツ', 'ひ、-び、-か', 'nichi, jitsu', 'hi, -bi, -ka', 'Hari, matahari', '日曜日', 'にちようび', 'Hari Minggu'),
  ('N5', '2', '一', 'イチ', 'ひと.つ', 'ichi', 'hitotsu', 'Satu', '一人', 'ひとり', 'Satu orang / sendirian'),
  ('N5', '3', '国', 'コク', 'くに', 'koku', 'kuni', 'Negara', '外国', 'がいこく', 'Luar negeri'),
  ('N5', '4', '人', 'ジン、ニン', 'ひと', 'jin, nin', 'hito', 'Orang', '日本人', 'にほんじん', 'Orang Jepang'),
  ('N5', '5', '年', 'ネン', 'とし', 'nen', 'toshi', 'Tahun', '今年', 'ことし', 'Tahun ini'),
  ('N5', '6', '大', 'ダイ、タイ', 'おお.きい', 'dai, tai', 'ookii', 'Besar', '大学', 'だいがく', 'Universitas'),
  ('N5', '7', '十', 'ジュウ', 'とお、と', 'juu', 'too, to', 'Sepuluh', '十月', 'じゅうがつ', 'Bulan Oktober'),
  ('N5', '8', '二', 'ニ', 'ふた.つ', 'ni', 'futatsu', 'Dua', '二人', 'ふたり', 'Dua orang'),
  ('N5', '9', '本', 'ホン', 'もと', 'hon', 'moto', 'Buku, asal', '日本', 'にほん', 'Jepang'),
  ('N5', '10', '中', 'チュウ', 'なか、うち', 'chuu', 'naka, uchi', 'Tengah, dalam', '中学校', 'ちゅうがっこう', 'Sekolah menengah pertama'),
  ('N5', '11', '長', 'チョウ', 'なが.い', 'chou', 'nagai', 'Panjang, pemimpin', '社長', 'しゃちょう', 'Direktur perusahaan'),
  ('N5', '12', '出', 'シュツ、スイ', 'で.る、だ.す', 'shutsu, sui', 'deru, dasu', 'Keluar', '出口', 'でぐち', 'Pintu keluar'),
  ('N5', '13', '三', 'サン', 'み.つ', 'san', 'mittsu', 'Tiga', '三月', 'さんがつ', 'Bulan Maret'),
  ('N5', '14', '時', 'ジ', 'とき', 'ji', 'toki', 'Waktu, jam', '時間', 'じかん', 'Waktu'),
  ('N5', '15', '行', 'コウ、ギョウ、アン', 'い.く、おこな.う', 'kou, gyou, an', 'iku, okonau', 'Pergi, melaksanakan', '旅行', 'りょこう', 'Perjalanan/wisata'),
  ('N5', '16', '見', 'ケン', 'み.る、み.える', 'ken', 'miru, mieru', 'Melihat', '見物', 'けんぶつ', 'Melihat-lihat'),
  ('N5', '17', '月', 'ゲツ、ガツ', 'つき', 'getsu, gatsu', 'tsuki', 'Bulan', '月曜日', 'げつようび', 'Hari Senin'),
  ('N5', '18', '分', 'ブン、フン、ブ', 'わ.ける', 'bun, fun, bu', 'wakeru', 'Bagian, menit', '自分', 'じぶん', 'Diri sendiri'),
  ('N5', '19', '後', 'ゴ、コウ', 'のち、うし.ろ、あと', 'go, kou', 'nochi, ushiro, ato', 'Belakang, kemudian', '午後', 'ごご', 'Siang/sore hari'),
  ('N5', '20', '前', 'ゼン', 'まえ', 'zen', 'mae', 'Depan, sebelum', '午前', 'ごぜん', 'Pagi hari'),
  ('N5', '21', '生', 'セイ、ショウ', 'い.きる、う.まれる、なま', 'sei, shou', 'ikiru, umareru, nama', 'Hidup, lahir', '先生', 'せんせい', 'Guru'),
  ('N5', '22', '五', 'ゴ', 'いつ.つ', 'go', 'itsutsu', 'Lima', '五月', 'ごがつ', 'Bulan Mei'),
  ('N5', '23', '間', 'カン、ケン', 'あいだ、ま', 'kan, ken', 'aida, ma', 'Ruang, jarak/interval', '人間', 'にんげん', 'Manusia'),
  ('N5', '24', '上', 'ジョウ、ショウ', 'うえ、うわ-、かみ、あ.げる、のぼ.る', 'jou, shou', 'ue, uwa, kami, ageru, noboru', 'Atas', '上手', 'じょうず', 'Pandai, mahir'),
  ('N5', '25', '東', 'トウ', 'ひがし', 'tou', 'higashi', 'Timur', '東京', 'とうきょう', 'Tokyo'),
  ('N5', '26', '四', 'シ', 'よ、よ.つ、よん', 'shi', 'yo, yotsu, yon', 'Empat', '四月', 'しがつ', 'Bulan April'),
  ('N5', '27', '今', 'コン', 'いま', 'kon', 'ima', 'Sekarang', '今日', 'きょう', 'Hari ini'),
  ('N5', '28', '金', 'キン、コン、ゴン', 'かね', 'kin, kon, gon', 'kane', 'Emas, uang', '金曜日', 'きんようび', 'Hari Jumat'),
  ('N5', '29', '九', 'キュウ、ク', 'ここの.つ', 'kyuu, ku', 'kokonotsu', 'Sembilan', '九月', 'くがつ', 'Bulan September'),
  ('N5', '30', '入', 'ニュウ', 'い.る、はい.る', 'nyuu', 'iru, hairu', 'Masuk', '入り口', 'いりぐち', 'Pintu masuk'),
  ('N5', '31', '学', 'ガク', 'まな.ぶ', 'gaku', 'manabu', 'Belajar, ilmu', '学生', 'がくせい', 'Siswa/mahasiswa'),
  ('N5', '32', '高', 'コウ', 'たか.い', 'kou', 'takai', 'Tinggi, mahal', '高校', 'こうこう', 'Sekolah menengah atas'),
  ('N5', '33', '円', 'エン', 'まる.い', 'en', 'marui', 'Bulat, yen', '千円', 'せんえん', 'Seribu yen'),
  ('N5', '34', '子', 'シ、ス、ツ', 'こ、ね', 'shi, su, tsu', 'ko, ne', 'Anak', '子供', 'こども', 'Anak-anak'),
  ('N5', '35', '外', 'ガイ、ゲ', 'そと、ほか、はず.す', 'gai, ge', 'soto, hoka, hazusu', 'Luar', '外国人', 'がいこくじん', 'Orang asing'),
  ('N5', '36', '八', 'ハチ', 'や、や.つ', 'hachi', 'ya, yatsu', 'Delapan', '八月', 'はちがつ', 'Bulan Agustus'),
  ('N5', '37', '六', 'ロク', 'む、む.つ', 'roku', 'mu, mutsu', 'Enam', '六月', 'ろくがつ', 'Bulan Juni'),
  ('N5', '38', '下', 'カ、ゲ', 'した、しも、さ.げる、くだ.る、お.ろす', 'ka, ge', 'shita, shimo, sageru, kudaru, orosu', 'Bawah', '下手', 'へた', 'Tidak pandai'),
  ('N5', '39', '来', 'ライ、タイ', 'く.る、きた.る', 'rai, tai', 'kuru, kitaru', 'Datang', '来週', 'らいしゅう', 'Minggu depan'),
  ('N5', '40', '気', 'キ、ケ', 'いき', 'ki, ke', 'iki', 'Semangat, udara', '元気', 'げんき', 'Sehat, bersemangat'),
  ('N5', '41', '小', 'ショウ', 'ちい.さい、こ-、お-', 'shou', 'chiisai, ko-, o-', 'Kecil', '小学校', 'しょうがっこう', 'Sekolah dasar'),
  ('N5', '42', '七', 'シチ', 'なな、なな.つ、なの', 'shichi', 'nana, nanatsu, nano', 'Tujuh', '七月', 'しちがつ', 'Bulan Juli'),
  ('N5', '43', '山', 'サン、セン', 'やま', 'san, sen', 'yama', 'Gunung', '富士山', 'ふじさん', 'Gunung Fuji'),
  ('N5', '44', '話', 'ワ', 'はな.す、はなし', 'wa', 'hanasu, hanashi', 'Berbicara, cerita', '電話', 'でんわ', 'Telepon'),
  ('N5', '45', '女', 'ジョ', 'おんな、め', 'jo', 'onna, me', 'Perempuan', '女性', 'じょせい', 'Wanita'),
  ('N5', '46', '北', 'ホク', 'きた', 'hoku', 'kita', 'Utara', '東北', 'とうほく', 'Timur laut / Tohoku'),
  ('N5', '47', '午', 'ゴ', 'うま', 'go', 'uma', 'Siang, kuda (shio)', '正午', 'しょうご', 'Tengah hari'),
  ('N5', '48', '百', 'ヒャク、ビャク', 'もも', 'hyaku, byaku', 'momo', 'Ratus', '百人', 'ひゃくにん', 'Seratus orang'),
  ('N5', '49', '書', 'ショ', 'か.く', 'sho', 'kaku', 'Menulis', '辞書', 'じしょ', 'Kamus'),
  ('N5', '50', '先', 'セン', 'さき、ま.ず', 'sen', 'saki, mazu', 'Sebelumnya, ujung', '先週', 'せんしゅう', 'Minggu lalu'),
  ('N5', '51', '名', 'メイ、ミョウ', 'な', 'mei, myou', 'na', 'Nama', '名前', 'なまえ', 'Nama'),
  ('N5', '52', '川', 'セン', 'かわ', 'sen', 'kawa', 'Sungai', '小川', 'おがわ', 'Anak sungai'),
  ('N5', '53', '千', 'セン', 'ち', 'sen', 'chi', 'Ribu', '千円', 'せんえん', 'Seribu yen'),
  ('N5', '54', '水', 'スイ', 'みず', 'sui', 'mizu', 'Air', '水曜日', 'すいようび', 'Hari Rabu'),
  ('N5', '55', '半', 'ハン', 'なか.ば', 'han', 'nakaba', 'Setengah, tengah', '半分', 'はんぶん', 'Setengah'),
  ('N5', '56', '男', 'ダン、ナン', 'おとこ、お', 'dan, nan', 'otoko, o', 'Laki-laki', '男性', 'だんせい', 'Pria'),
  ('N5', '57', '西', 'セイ、サイ', 'にし', 'sei, sai', 'nishi', 'Barat', '関西', 'かんさい', 'Kansai (wilayah barat Jepang)'),
  ('N5', '58', '電', 'デン', '-', 'den', '-', 'Listrik', '電気', 'でんき', 'Listrik'),
  ('N5', '59', '校', 'コウ', '-', 'kou', '-', 'Sekolah', '学校', 'がっこう', 'Sekolah'),
  ('N5', '60', '語', 'ゴ', 'かた.る', 'go', 'kataru', 'Kata, bahasa', '日本語', 'にほんご', 'Bahasa Jepang'),
  ('N5', '61', '土', 'ド、ト', 'つち', 'do, to', 'tsuchi', 'Tanah', '土曜日', 'どようび', 'Hari Sabtu'),
  ('N5', '62', '木', 'ボク、モク', 'き、こ-', 'boku, moku', 'ki, ko-', 'Pohon, kayu', '木曜日', 'もくようび', 'Hari Kamis'),
  ('N5', '63', '聞', 'ブン、モン', 'き.く', 'bun, mon', 'kiku', 'Mendengar, bertanya', '新聞', 'しんぶん', 'Koran'),
  ('N5', '64', '食', 'ショク、ジキ', 'く.う、た.べる、は.む', 'shoku, jiki', 'kuu, taberu, hamu', 'Makan', '食事', 'しょくじ', 'Makan/santap'),
  ('N5', '65', '車', 'シャ', 'くるま', 'sha', 'kuruma', 'Mobil, roda', '自転車', 'じてんしゃ', 'Sepeda'),
  ('N5', '66', '何', 'カ', 'なに、なん', 'ka', 'nani, nan', 'Apa', '何時', 'なんじ', 'Jam berapa'),
  ('N5', '67', '南', 'ナン、ナ', 'みなみ', 'nan, na', 'minami', 'Selatan', '南口', 'みなみぐち', 'Pintu selatan'),
  ('N5', '68', '万', 'マン、バン', '-', 'man, ban', '-', 'Sepuluh ribu', '一万円', 'いちまんえん', 'Sepuluh ribu yen'),
  ('N5', '69', '毎', 'マイ', 'ごと.に', 'mai', 'gotoni', 'Setiap', '毎日', 'まいにち', 'Setiap hari'),
  ('N5', '70', '白', 'ハク、ビャク', 'しろ.い', 'haku, byaku', 'shiroi', 'Putih', '白い', 'しろい', 'Putih'),
  ('N5', '71', '天', 'テン', '-', 'ten', '-', 'Langit', '天気', 'てんき', 'Cuaca'),
  ('N5', '72', '母', 'ボ', 'はは、かあ', 'bo', 'haha, kaa', 'Ibu', '母親', 'ははおや', 'Ibu (kandung)'),
  ('N5', '73', '火', 'カ', 'ひ、-び、ほ-', 'ka', 'hi, -bi, ho-', 'Api', '火曜日', 'かようび', 'Hari Selasa'),
  ('N5', '74', '右', 'ウ、ユウ', 'みぎ', 'u, yuu', 'migi', 'Kanan', '右手', 'みぎて', 'Tangan kanan'),
  ('N5', '75', '読', 'ドク、トク、トウ', 'よ.む', 'doku, toku, tou', 'yomu', 'Membaca', '読書', 'どくしょ', 'Membaca buku'),
  ('N5', '76', '友', 'ユウ', 'とも', 'yuu', 'tomo', 'Teman', '友達', 'ともだち', 'Teman'),
  ('N5', '77', '左', 'サ、シャ', 'ひだり', 'sa, sha', 'hidari', 'Kiri', '左手', 'ひだりて', 'Tangan kiri'),
  ('N5', '78', '休', 'キュウ', 'やす.む', 'kyuu', 'yasumu', 'Istirahat, libur', '休み', 'やすみ', 'Libur/istirahat'),
  ('N5', '79', '父', 'フ', 'ちち、とう', 'fu', 'chichi, tou', 'Ayah', '父親', 'ちちおや', 'Ayah (kandung)'),
  ('N5', '80', '雨', 'ウ', 'あめ、あま', 'u', 'ame, ama', 'Hujan', '大雨', 'おおあめ', 'Hujan lebat');
