-- Auto-generated dari kosakata_n5.json — jangan edit manual, edit file JSON lalu jalankan ulang script ini
DELETE FROM kosakata WHERE level = 'N5';
INSERT INTO kosakata (level, nomor, kata, kanji, hiragana, romaji, arti, kelas_kata, contoh_kalimat, contoh_hiragana, contoh_arti) VALUES
  ('N5', '1', 'わたし', '私', 'わたし', 'watashi', 'Saya', 'Kata benda', 'わたしは がくせいです。', 'わたしは がくせいです。', 'Saya adalah siswa.'),
  ('N5', '2', 'たべる', '食べる', 'たべる', 'taberu', 'Makan', 'Kata kerja', 'まいにち ごはんを たべます。', 'まいにち ごはんを たべます。', 'Saya makan nasi setiap hari.'),
  ('N5', '3', 'のむ', '飲む', 'のむ', 'nomu', 'Minum', 'Kata kerja', 'みずを のみます。', 'みずを のみます。', 'Saya minum air.'),
  ('N5', '4', 'がっこう', '学校', 'がっこう', 'gakkou', 'Sekolah', 'Kata benda', 'がっこうへ いきます。', 'がっこうへ いきます。', 'Saya pergi ke sekolah.'),
  ('N5', '5', 'ともだち', '友達', 'ともだち', 'tomodachi', 'Teman', 'Kata benda', 'ともだちと はなします。', 'ともだちと はなします。', 'Saya bicara dengan teman.'),
  ('N5', '6', 'おおきい', '大きい', 'おおきい', 'ookii', 'Besar', 'Kata sifat', 'この いえは おおきいです。', 'この いえは おおきいです。', 'Rumah ini besar.'),
  ('N5', '7', 'ちいさい', '小さい', 'ちいさい', 'chiisai', 'Kecil', 'Kata sifat', 'その いぬは ちいさいです。', 'その いぬは ちいさいです。', 'Anjing itu kecil.'),
  ('N5', '8', 'みず', '水', 'みず', 'mizu', 'Air', 'Kata benda', 'みずを ください。', 'みずを ください。', 'Tolong berikan air.'),
  ('N5', '9', 'しごと', '仕事', 'しごと', 'shigoto', 'Pekerjaan', 'Kata benda', 'しごとは たのしいです。', 'しごとは たのしいです。', 'Pekerjaan itu menyenangkan.'),
  ('N5', '10', 'はやい', '早い', 'はやい', 'hayai', 'Cepat, awal', 'Kata sifat', 'けさは はやく おきました。', 'けさは はやく おきました。', 'Pagi ini saya bangun lebih awal.'),
  ('N5', '11', 'あるく', '歩く', 'あるく', 'aruku', 'Berjalan kaki', 'Kata kerja', 'こうえんを あるきます。', 'こうえんを あるきます。', 'Saya berjalan di taman.'),
  ('N5', '12', 'かう', '買う', 'かう', 'kau', 'Membeli', 'Kata kerja', 'スーパーで やさいを かいます。', 'すーぱーで やさいを かいます。', 'Saya membeli sayur di supermarket.'),
  ('N5', '13', 'でんわ', '電話', 'でんわ', 'denwa', 'Telepon', 'Kata benda', 'でんわを かけます。', 'でんわを かけます。', 'Saya menelepon.'),
  ('N5', '14', 'あたらしい', '新しい', 'あたらしい', 'atarashii', 'Baru', 'Kata sifat', 'あたらしい くつを かいました。', 'あたらしい くつを かいました。', 'Saya membeli sepatu baru.'),
  ('N5', '15', 'やすい', '安い', 'やすい', 'yasui', 'Murah', 'Kata sifat', 'この みせは やすいです。', 'この みせは やすいです。', 'Toko ini murah.'),
  ('N5', '16', 'たかい', '高い', 'たかい', 'takai', 'Mahal, tinggi', 'Kata sifat', 'あの たてものは たかいです。', 'あの たてものは たかいです。', 'Gedung itu tinggi.'),
  ('N5', '17', 'びょういん', '病院', 'びょういん', 'byouin', 'Rumah sakit', 'Kata benda', 'びょういんへ いきます。', 'びょういんへ いきます。', 'Saya pergi ke rumah sakit.'),
  ('N5', '18', 'つかう', '使う', 'つかう', 'tsukau', 'Menggunakan', 'Kata kerja', 'パソコンを つかいます。', 'ぱそこんを つかいます。', 'Saya menggunakan komputer.'),
  ('N5', '19', 'まいにち', '毎日', 'まいにち', 'mainichi', 'Setiap hari', 'Kata keterangan', 'まいにち べんきょうします。', 'まいにち べんきょうします。', 'Saya belajar setiap hari.'),
  ('N5', '20', 'げんき', '元気', 'げんき', 'genki', 'Sehat, semangat', 'Kata sifat-na', 'げんきですか。', 'げんきですか。', 'Apakah kamu sehat?'),
  ('N5', '21', 'しずか', '静か', 'しずか', 'shizuka', 'Tenang, sepi', 'Kata sifat-na', 'この へやは しずかです。', 'この へやは しずかです。', 'Kamar ini tenang.'),
  ('N5', '22', 'べんり', '便利', 'べんり', 'benri', 'Praktis, nyaman', 'Kata sifat-na', 'この アプリは べんりです。', 'この あぷりは べんりです。', 'Aplikasi ini praktis.'),
  ('N5', '23', 'いそがしい', '忙しい', 'いそがしい', 'isogashii', 'Sibuk', 'Kata sifat', 'きょうは いそがしいです。', 'きょうは いそがしいです。', 'Hari ini saya sibuk.'),
  ('N5', '24', 'たのしい', '楽しい', 'たのしい', 'tanoshii', 'Menyenangkan', 'Kata sifat', 'りょこうは たのしいです。', 'りょこうは たのしいです。', 'Perjalanan itu menyenangkan.'),
  ('N5', '25', 'はなす', '話す', 'はなす', 'hanasu', 'Berbicara', 'Kata kerja', 'にほんごで はなします。', 'にほんごで はなします。', 'Saya berbicara dalam bahasa Jepang.'),
  ('N5', '26', 'きく', '聞く', 'きく', 'kiku', 'Mendengar, bertanya', 'Kata kerja', 'おんがくを ききます。', 'おんがくを ききます。', 'Saya mendengarkan musik.'),
  ('N5', '27', 'みる', '見る', 'みる', 'miru', 'Melihat', 'Kata kerja', 'テレビを みます。', 'てれびを みます。', 'Saya menonton televisi.'),
  ('N5', '28', 'かく', '書く', 'かく', 'kaku', 'Menulis', 'Kata kerja', 'てがみを かきます。', 'てがみを かきます。', 'Saya menulis surat.'),
  ('N5', '29', 'あさ', '朝', 'あさ', 'asa', 'Pagi', 'Kata benda', 'あさ ろくじに おきます。', 'あさ ろくじに おきます。', 'Saya bangun jam 6 pagi.'),
  ('N5', '30', 'よる', '夜', 'よる', 'yoru', 'Malam', 'Kata benda', 'よる はやく ねます。', 'よる はやく ねます。', 'Saya tidur lebih awal di malam hari.');
