-- Auto-generated dari kanji_n4.json — jangan edit manual, edit file JSON lalu jalankan ulang script ini
DELETE FROM kanji WHERE level = 'N4';
INSERT INTO kanji (level, nomor, kanji, onyomi, kunyomi, romaji_onyomi, romaji_kunyomi, arti, contoh_kata, contoh_hiragana, contoh_arti) VALUES
  ('N4', '1', '会', 'カイ', 'あ.う', 'kai', 'au', 'Bertemu, perkumpulan', '会社', 'かいしゃ', 'Perusahaan'),
  ('N4', '2', '同', 'ドウ', 'おな.じ', 'dou', 'onaji', 'Sama', '同じ', 'おなじ', 'Sama'),
  ('N4', '3', '事', 'ジ', 'こと', 'ji', 'koto', 'Hal, perkara', '仕事', 'しごと', 'Pekerjaan'),
  ('N4', '4', '自', 'ジ、シ', 'みずか.ら', 'ji, shi', 'mizukara', 'Diri sendiri', '自分', 'じぶん', 'Diri sendiri'),
  ('N4', '5', '社', 'シャ', 'やしろ', 'sha', 'yashiro', 'Perusahaan, kuil', '社会', 'しゃかい', 'Masyarakat'),
  ('N4', '6', '発', 'ハツ、ホツ', '-', 'hatsu, hotsu', '-', 'Berangkat, timbul', '出発', 'しゅっぱつ', 'Keberangkatan'),
  ('N4', '7', '者', 'シャ', 'もの', 'sha', 'mono', 'Orang (pelaku)', '医者', 'いしゃ', 'Dokter'),
  ('N4', '8', '地', 'チ、ジ', '-', 'chi, ji', '-', 'Tanah, bumi', '地図', 'ちず', 'Peta'),
  ('N4', '9', '業', 'ギョウ', 'わざ', 'gyou', 'waza', 'Usaha, pekerjaan', '授業', 'じゅぎょう', 'Pelajaran/kelas'),
  ('N4', '10', '方', 'ホウ', 'かた', 'hou', 'kata', 'Arah, cara, orang', '使い方', 'つかいかた', 'Cara pemakaian'),
  ('N4', '11', '新', 'シン', 'あたら.しい、あら.た', 'shin', 'atarashii, arata', 'Baru', '新聞', 'しんぶん', 'Koran'),
  ('N4', '12', '場', 'ジョウ', 'ば', 'jou', 'ba', 'Tempat', '工場', 'こうじょう', 'Pabrik'),
  ('N4', '13', '員', 'イン', '-', 'in', '-', 'Anggota, pegawai', '会社員', 'かいしゃいん', 'Karyawan'),
  ('N4', '14', '立', 'リツ', 'た.つ', 'ritsu', 'tatsu', 'Berdiri', '国立', 'こくりつ', 'Negeri (milik negara)'),
  ('N4', '15', '開', 'カイ', 'ひら.く、あ.ける', 'kai', 'hiraku, akeru', 'Membuka', '開始', 'かいし', 'Permulaan'),
  ('N4', '16', '手', 'シュ', 'て', 'shu', 'te', 'Tangan, pandai', '選手', 'せんしゅ', 'Atlet'),
  ('N4', '17', '力', 'リョク、リキ', 'ちから', 'ryoku, riki', 'chikara', 'Kekuatan', '努力', 'どりょく', 'Usaha keras'),
  ('N4', '18', '問', 'モン', 'と.う', 'mon', 'tou', 'Bertanya', '質問', 'しつもん', 'Pertanyaan'),
  ('N4', '19', '代', 'ダイ', 'か.わり', 'dai', 'kawari', 'Generasi, pengganti', '時代', 'じだい', 'Zaman'),
  ('N4', '20', '明', 'メイ、ミョウ', 'あか.るい', 'mei, myou', 'akarui', 'Terang, jelas', '説明', 'せつめい', 'Penjelasan'),
  ('N4', '21', '動', 'ドウ', 'うご.く', 'dou', 'ugoku', 'Bergerak', '運動', 'うんどう', 'Olahraga'),
  ('N4', '22', '京', 'キョウ、ケイ、キン', 'みやこ', 'kyou, kei, kin', 'miyako', 'Ibu kota', '東京', 'とうきょう', 'Tokyo'),
  ('N4', '23', '目', 'モク、ボク', 'め', 'moku, boku', 'me', 'Mata, urutan ke-', '目的', 'もくてき', 'Tujuan'),
  ('N4', '24', '通', 'ツウ', 'とお.る、かよ.う', 'tsuu', 'tooru, kayou', 'Melewati, lalu lintas', '交通', 'こうつう', 'Lalu lintas'),
  ('N4', '25', '言', 'ゲン、ゴン', 'い.う、こと', 'gen, gon', 'iu, koto', 'Berkata, kata', '言葉', 'ことば', 'Kata, bahasa'),
  ('N4', '26', '理', 'リ', '-', 'ri', '-', 'Logika, susunan', '料理', 'りょうり', 'Masakan'),
  ('N4', '27', '体', 'タイ', 'からだ', 'tai', 'karada', 'Badan, tubuh', '体育', 'たいいく', 'Pendidikan jasmani'),
  ('N4', '28', '田', 'デン', 'た', 'den', 'ta', 'Sawah', '田舎', 'いなか', 'Pedesaan/kampung'),
  ('N4', '29', '主', 'シュ', 'ぬし、おも', 'shu', 'nushi, omo', 'Tuan, utama', '主人', 'しゅじん', 'Suami/tuan rumah'),
  ('N4', '30', '題', 'ダイ', '-', 'dai', '-', 'Judul, topik', '問題', 'もんだい', 'Masalah/soal'),
  ('N4', '31', '意', 'イ', '-', 'i', '-', 'Pikiran, makna', '意味', 'いみ', 'Arti/makna'),
  ('N4', '32', '不', 'フ、ブ', '-', 'fu, bu', '-', 'Tidak, bukan', '不安', 'ふあん', 'Cemas'),
  ('N4', '33', '作', 'サク、サ', 'つく.る', 'saku, sa', 'tsukuru', 'Membuat', '作文', 'さくぶん', 'Karangan'),
  ('N4', '34', '用', 'ヨウ', 'もち.いる', 'you', 'mochiiru', 'Menggunakan', '使用', 'しよう', 'Penggunaan'),
  ('N4', '35', '度', 'ド、タク', 'たび', 'do, taku', 'tabi', 'Kali, derajat', '今度', 'こんど', 'Kali ini/lain kali'),
  ('N4', '36', '強', 'キョウ、ゴウ', 'つよ.い', 'kyou, gou', 'tsuyoi', 'Kuat', '勉強', 'べんきょう', 'Belajar'),
  ('N4', '37', '公', 'コウ', '-', 'kou', '-', 'Umum, publik', '公園', 'こうえん', 'Taman kota'),
  ('N4', '38', '持', 'ジ', 'も.つ', 'ji', 'motsu', 'Membawa, memiliki', '気持ち', 'きもち', 'Perasaan'),
  ('N4', '39', '野', 'ヤ', 'の', 'ya', 'no', 'Padang, liar', '野菜', 'やさい', 'Sayuran'),
  ('N4', '40', '以', 'イ', 'も.って', 'i', 'motte', 'Dengan, berdasarkan', '以上', 'いじょう', 'Lebih dari, di atas'),
  ('N4', '41', '思', 'シ', 'おも.う', 'shi', 'omou', 'Berpikir', '思い出', 'おもいで', 'Kenangan'),
  ('N4', '42', '家', 'カ', 'いえ、や、うち', 'ka', 'ie, ya, uchi', 'Rumah, keluarga', '家族', 'かぞく', 'Keluarga'),
  ('N4', '43', '世', 'セイ、セ', 'よ', 'sei, se', 'yo', 'Dunia, generasi', '世界', 'せかい', 'Dunia'),
  ('N4', '44', '多', 'タ', 'おお.い', 'ta', 'ooi', 'Banyak', '多分', 'たぶん', 'Mungkin/barangkali'),
  ('N4', '45', '正', 'セイ、ショウ', 'ただ.しい、まさ.に', 'sei, shou', 'tadashii, masani', 'Benar', '正月', 'しょうがつ', 'Tahun baru (Jepang)'),
  ('N4', '46', '安', 'アン', 'やす.い', 'an', 'yasui', 'Aman, murah', '安心', 'あんしん', 'Merasa tenang'),
  ('N4', '47', '院', 'イン', '-', 'in', '-', 'Institusi, rumah sakit', '病院', 'びょういん', 'Rumah sakit'),
  ('N4', '48', '心', 'シン', 'こころ', 'shin', 'kokoro', 'Hati, pikiran', '心配', 'しんぱい', 'Khawatir'),
  ('N4', '49', '界', 'カイ', '-', 'kai', '-', 'Dunia, batas', '業界', 'ぎょうかい', 'Dunia industri'),
  ('N4', '50', '教', 'キョウ', 'おし.える、おそ.わる', 'kyou', 'oshieru, osowaru', 'Mengajar', '教室', 'きょうしつ', 'Ruang kelas'),
  ('N4', '51', '文', 'ブン、モン', 'ふみ', 'bun, mon', 'fumi', 'Kalimat, tulisan', '文化', 'ぶんか', 'Kebudayaan'),
  ('N4', '52', '元', 'ゲン、ガン', 'もと', 'gen, gan', 'moto', 'Asal, awal', '元気', 'げんき', 'Sehat/semangat'),
  ('N4', '53', '重', 'ジュウ、チョウ', 'おも.い、かさ.ねる', 'juu, chou', 'omoi, kasaneru', 'Berat, penting', '重要', 'じゅうよう', 'Penting'),
  ('N4', '54', '近', 'キン', 'ちか.い', 'kin', 'chikai', 'Dekat', '近所', 'きんじょ', 'Sekitar/tetangga'),
  ('N4', '55', '考', 'コウ', 'かんが.える', 'kou', 'kangaeru', 'Berpikir, mempertimbangkan', '考え方', 'かんがえかた', 'Cara berpikir'),
  ('N4', '56', '画', 'ガ、カク', '-', 'ga, kaku', '-', 'Gambar, lukisan', '映画', 'えいが', 'Film'),
  ('N4', '57', '海', 'カイ', 'うみ', 'kai', 'umi', 'Laut', '海外', 'かいがい', 'Luar negeri'),
  ('N4', '58', '売', 'バイ', 'う.る', 'bai', 'uru', 'Menjual', '売店', 'ばいてん', 'Kios/toko kecil'),
  ('N4', '59', '知', 'チ', 'し.る', 'chi', 'shiru', 'Mengetahui', '知識', 'ちしき', 'Pengetahuan'),
  ('N4', '60', '道', 'ドウ', 'みち', 'dou', 'michi', 'Jalan', '道路', 'どうろ', 'Jalan raya'),
  ('N4', '61', '集', 'シュウ', 'あつ.める', 'shuu', 'atsumeru', 'Mengumpulkan', '集合', 'しゅうごう', 'Berkumpul'),
  ('N4', '62', '別', 'ベツ', 'わか.れる、わ.ける', 'betsu', 'wakareru, wakeru', 'Berpisah, terpisah', '別々', 'べつべつ', 'Terpisah/sendiri-sendiri'),
  ('N4', '63', '物', 'ブツ、モツ', 'もの', 'butsu, motsu', 'mono', 'Barang, benda', '荷物', 'にもつ', 'Barang bawaan'),
  ('N4', '64', '使', 'シ', 'つか.う', 'shi', 'tsukau', 'Menggunakan', '大使', 'たいし', 'Duta besar'),
  ('N4', '65', '品', 'ヒン', 'しな', 'hin', 'shina', 'Barang, mutu', '商品', 'しょうひん', 'Barang dagangan'),
  ('N4', '66', '計', 'ケイ', 'はか.る', 'kei', 'hakaru', 'Rencana, mengukur', '時計', 'とけい', 'Jam (arloji)'),
  ('N4', '67', '死', 'シ', 'し.ぬ', 'shi', 'shinu', 'Mati', '死亡', 'しぼう', 'Kematian'),
  ('N4', '68', '特', 'トク', '-', 'toku', '-', 'Khusus', '特別', 'とくべつ', 'Istimewa/khusus'),
  ('N4', '69', '私', 'シ', 'わたくし、わたし', 'shi', 'watakushi, watashi', 'Pribadi, saya', '私立', 'しりつ', 'Swasta'),
  ('N4', '70', '始', 'シ', 'はじ.める', 'shi', 'hajimeru', 'Memulai', '始発', 'しはつ', 'Keberangkatan pertama'),
  ('N4', '71', '朝', 'チョウ', 'あさ', 'chou', 'asa', 'Pagi', '朝食', 'ちょうしょく', 'Sarapan'),
  ('N4', '72', '運', 'ウン', 'はこ.ぶ', 'un', 'hakobu', 'Membawa, nasib', '運転', 'うんてん', 'Mengemudi'),
  ('N4', '73', '終', 'シュウ', 'お.わる', 'shuu', 'owaru', 'Berakhir', '終電', 'しゅうでん', 'Kereta terakhir'),
  ('N4', '74', '台', 'ダイ、タイ', '-', 'dai, tai', '-', 'Alas, penghitung mesin/kendaraan', '台風', 'たいふう', 'Topan/badai'),
  ('N4', '75', '広', 'コウ', 'ひろ.い', 'kou', 'hiroi', 'Luas', '広告', 'こうこく', 'Iklan'),
  ('N4', '76', '住', 'ジュウ、チュウ', 'す.む', 'juu, chuu', 'sumu', 'Tinggal, berdiam', '住所', 'じゅうしょ', 'Alamat'),
  ('N4', '77', '無', 'ム、ブ', 'な.い', 'mu, bu', 'nai', 'Tidak ada', '無料', 'むりょう', 'Gratis'),
  ('N4', '78', '真', 'シン', 'ま、まこと', 'shin', 'ma, makoto', 'Sungguh, asli', '写真', 'しゃしん', 'Foto'),
  ('N4', '79', '有', 'ユウ、ウ', 'あ.る', 'yuu, u', 'aru', 'Memiliki, ada', '有名', 'ゆうめい', 'Terkenal'),
  ('N4', '80', '口', 'コウ', 'くち', 'kou', 'kuchi', 'Mulut', '入り口', 'いりぐち', 'Pintu masuk'),
  ('N4', '81', '少', 'ショウ', 'すく.ない、すこ.し', 'shou', 'sukunai, sukoshi', 'Sedikit', '少し', 'すこし', 'Sedikit'),
  ('N4', '82', '町', 'チョウ', 'まち', 'chou', 'machi', 'Kota kecil, kelurahan', '町内', 'ちょうない', 'Lingkungan setempat'),
  ('N4', '83', '料', 'リョウ', '-', 'ryou', '-', 'Biaya, bahan', '料金', 'りょうきん', 'Biaya/tarif'),
  ('N4', '84', '工', 'コウ、ク、グ', '-', 'kou, ku, gu', '-', 'Kerajinan, konstruksi', '工事', 'こうじ', 'Konstruksi/pembangunan'),
  ('N4', '85', '建', 'ケン、コン', 'た.てる', 'ken, kon', 'tateru', 'Membangun', '建物', 'たてもの', 'Bangunan'),
  ('N4', '86', '空', 'クウ', 'そら、から、あ.く、す.く', 'kuu', 'sora, kara, aku, suku', 'Kosong, langit', '空港', 'くうこう', 'Bandara'),
  ('N4', '87', '急', 'キュウ', 'いそ.ぐ', 'kyuu', 'isogu', 'Buru-buru, mendadak', '急行', 'きゅうこう', 'Kereta cepat'),
  ('N4', '88', '止', 'シ', 'と.まる、とど.まる、や.める', 'shi', 'tomaru, todomaru, yameru', 'Berhenti', '中止', 'ちゅうし', 'Pembatalan'),
  ('N4', '89', '送', 'ソウ', 'おく.る', 'sou', 'okuru', 'Mengirim, mengantar', '送料', 'そうりょう', 'Biaya kirim'),
  ('N4', '90', '切', 'セツ、サイ', 'き.る', 'setsu, sai', 'kiru', 'Memotong', '切符', 'きっぷ', 'Tiket'),
  ('N4', '91', '転', 'テン', 'ころ.がる', 'ten', 'korogaru', 'Berputar, berpindah', '自転車', 'じてんしゃ', 'Sepeda'),
  ('N4', '92', '研', 'ケン', 'と.ぐ', 'ken', 'togu', 'Mengasah, meneliti', '研修', 'けんしゅう', 'Pelatihan'),
  ('N4', '93', '足', 'ソク', 'あし、た.りる', 'soku', 'ashi, tariru', 'Kaki, cukup', '足りる', 'たりる', 'Mencukupi'),
  ('N4', '94', '究', 'キュウ', '-', 'kyuu', '-', 'Meneliti', '研究', 'けんきゅう', 'Penelitian'),
  ('N4', '95', '楽', 'ガク、ラク', 'たの.しい', 'gaku, raku', 'tanoshii', 'Musik, senang', '音楽', 'おんがく', 'Musik'),
  ('N4', '96', '起', 'キ', 'お.きる、おこ.す', 'ki', 'okiru, okosu', 'Bangun, terjadi', '起床', 'きしょう', 'Bangun tidur'),
  ('N4', '97', '着', 'チャク', 'き.る、つ.く', 'chaku', 'kiru, tsuku', 'Sampai, memakai', '到着', 'とうちゃく', 'Kedatangan/tiba'),
  ('N4', '98', '店', 'テン', 'みせ', 'ten', 'mise', 'Toko', '店員', 'てんいん', 'Pegawai toko'),
  ('N4', '99', '病', 'ビョウ', 'や.む', 'byou', 'yamu', 'Sakit', '病気', 'びょうき', 'Penyakit/sakit'),
  ('N4', '100', '質', 'シツ、シチ', 'たち、ただ.す', 'shitsu, shichi', 'tachi, tadasu', 'Kualitas, sifat', '品質', 'ひんしつ', 'Kualitas barang'),
  ('N4', '101', '待', 'タイ', 'ま.つ', 'tai', 'matsu', 'Menunggu', '期待', 'きたい', 'Harapan'),
  ('N4', '102', '試', 'シ', 'こころ.みる、ため.す', 'shi', 'kokoromiru, tamesu', 'Mencoba, ujian', '試験', 'しけん', 'Ujian'),
  ('N4', '103', '族', 'ゾク', '-', 'zoku', '-', 'Suku, keluarga', '民族', 'みんぞく', 'Suku bangsa'),
  ('N4', '104', '銀', 'ギン', '-', 'gin', '-', 'Perak', '銀行', 'ぎんこう', 'Bank'),
  ('N4', '105', '早', 'ソウ、サッ', 'はや.い', 'sou, sa', 'hayai', 'Cepat, awal', '早朝', 'そうちょう', 'Pagi-pagi sekali'),
  ('N4', '106', '映', 'エイ', 'うつ.る、は.える', 'ei', 'utsuru, haeru', 'Memantul, tercermin', '映像', 'えいぞう', 'Citra/gambar video'),
  ('N4', '107', '親', 'シン', 'おや、した.しい', 'shin', 'oya, shitashii', 'Orang tua, akrab', '親切', 'しんせつ', 'Ramah/baik hati'),
  ('N4', '108', '験', 'ケン', '-', 'ken', '-', 'Verifikasi, uji', '経験', 'けいけん', 'Pengalaman'),
  ('N4', '109', '英', 'エイ', '-', 'ei', '-', 'Inggris, unggul', '英語', 'えいご', 'Bahasa Inggris'),
  ('N4', '110', '医', 'イ', '-', 'i', '-', 'Dokter, pengobatan', '医院', 'いいん', 'Klinik'),
  ('N4', '111', '仕', 'シ', '-', 'shi', '-', 'Melayani, bekerja', '仕方', 'しかた', 'Cara melakukan'),
  ('N4', '112', '去', 'キョ、コ', 'さ.る', 'kyo, ko', 'saru', 'Berlalu, pergi', '過去', 'かこ', 'Masa lalu'),
  ('N4', '113', '味', 'ミ', 'あじ', 'mi', 'aji', 'Rasa', '興味', 'きょうみ', 'Minat'),
  ('N4', '114', '写', 'シャ', 'うつ.る', 'sha', 'utsuru', 'Menyalin, memotret', '写生', 'しゃせい', 'Melukis dari alam'),
  ('N4', '115', '字', 'ジ', '-', 'ji', '-', 'Huruf, karakter', '漢字', 'かんじ', 'Kanji'),
  ('N4', '116', '答', 'トウ', 'こた.える', 'tou', 'kotaeru', 'Menjawab', '答え', 'こたえ', 'Jawaban'),
  ('N4', '117', '夜', 'ヤ', 'よ、よる', 'ya', 'yo, yoru', 'Malam', '夜中', 'よなか', 'Tengah malam'),
  ('N4', '118', '音', 'オン', 'おと、ね', 'on', 'oto, ne', 'Suara, bunyi', '音声', 'おんせい', 'Suara/audio'),
  ('N4', '119', '注', 'チュウ', 'そそ.ぐ、さ.す', 'chuu', 'sosogu, sasu', 'Menuang, memperhatikan', '注意', 'ちゅうい', 'Perhatian/hati-hati'),
  ('N4', '120', '帰', 'キ', 'かえ.る、かえ.す', 'ki', 'kaeru, kaesu', 'Pulang', '帰国', 'きこく', 'Pulang ke negara asal'),
  ('N4', '121', '古', 'コ', 'ふる.い', 'ko', 'furui', 'Lama, kuno', '中古', 'ちゅうこ', 'Barang bekas'),
  ('N4', '122', '歌', 'カ', 'うた、うた.う', 'ka', 'uta, utau', 'Lagu, bernyanyi', '歌手', 'かしゅ', 'Penyanyi'),
  ('N4', '123', '買', 'バイ', 'か.う', 'bai', 'kau', 'Membeli', '買い物', 'かいもの', 'Belanja'),
  ('N4', '124', '悪', 'アク', 'わる.い', 'aku', 'warui', 'Buruk, jahat', '悪い', 'わるい', 'Buruk/jahat'),
  ('N4', '125', '図', 'ズ、ト', 'はか.る', 'zu, to', 'hakaru', 'Peta, gambar', '地図', 'ちず', 'Peta'),
  ('N4', '126', '週', 'シュウ', '-', 'shuu', '-', 'Minggu (pekan)', '週間', 'しゅうかん', 'Kurun waktu seminggu'),
  ('N4', '127', '室', 'シツ', 'むろ', 'shitsu', 'muro', 'Kamar, ruangan', '地下室', 'ちかしつ', 'Ruang bawah tanah'),
  ('N4', '128', '歩', 'ホ、ブ', 'ある.く、あゆ.む', 'ho, bu', 'aruku, ayumu', 'Berjalan', '散歩', 'さんぽ', 'Jalan-jalan'),
  ('N4', '129', '風', 'フウ、フ', 'かぜ、かざ-', 'fuu, fu', 'kaze, kaza-', 'Angin, gaya', '風邪', 'かぜ', 'Masuk angin/flu'),
  ('N4', '130', '紙', 'シ', 'かみ', 'shi', 'kami', 'Kertas', '手紙', 'てがみ', 'Surat'),
  ('N4', '131', '黒', 'コク', 'くろ', 'koku', 'kuro', 'Hitam', '黒い', 'くろい', 'Hitam'),
  ('N4', '132', '花', 'カ、ケ', 'はな', 'ka, ke', 'hana', 'Bunga', '花見', 'はなみ', 'Menikmati bunga sakura'),
  ('N4', '133', '春', 'シュン', 'はる', 'shun', 'haru', 'Musim semi', '春休み', 'はるやすみ', 'Libur musim semi'),
  ('N4', '134', '赤', 'セキ、シャク', 'あか.い', 'seki, shaku', 'akai', 'Merah', '赤い', 'あかい', 'Merah'),
  ('N4', '135', '青', 'セイ、ショウ', 'あお.い', 'sei, shou', 'aoi', 'Biru', '青い', 'あおい', 'Biru'),
  ('N4', '136', '館', 'カン', 'やかた', 'kan', 'yakata', 'Gedung, aula', '図書館', 'としょかん', 'Perpustakaan'),
  ('N4', '137', '屋', 'オク', 'や', 'oku', 'ya', 'Atap, toko', '部屋', 'へや', 'Kamar'),
  ('N4', '138', '色', 'ショク、シキ', 'いろ', 'shoku, shiki', 'iro', 'Warna', '色々', 'いろいろ', 'Bermacam-macam'),
  ('N4', '139', '走', 'ソウ', 'はし.る', 'sou', 'hashiru', 'Berlari', '走る', 'はしる', 'Berlari'),
  ('N4', '140', '秋', 'シュウ', 'あき', 'shuu', 'aki', 'Musim gugur', '秋田', 'あきた', 'Prefektur Akita'),
  ('N4', '141', '夏', 'カ、ゲ', 'なつ', 'ka, ge', 'natsu', 'Musim panas', '夏休み', 'なつやすみ', 'Libur musim panas'),
  ('N4', '142', '習', 'シュウ', 'なら.う', 'shuu', 'narau', 'Belajar/berlatih', '習慣', 'しゅうかん', 'Kebiasaan'),
  ('N4', '143', '駅', 'エキ', '-', 'eki', '-', 'Stasiun', '駅員', 'えきいん', 'Petugas stasiun'),
  ('N4', '144', '洋', 'ヨウ', '-', 'you', '-', 'Laut, gaya barat', '洋服', 'ようふく', 'Baju bergaya barat'),
  ('N4', '145', '旅', 'リョ', 'たび', 'ryo', 'tabi', 'Perjalanan', '旅行', 'りょこう', 'Perjalanan/wisata'),
  ('N4', '146', '服', 'フク', '-', 'fuku', '-', 'Pakaian', '服装', 'ふくそう', 'Cara berpakaian'),
  ('N4', '147', '夕', '-', 'ゆう', '-', 'yuu', 'Sore/senja', '夕方', 'ゆうがた', 'Waktu sore'),
  ('N4', '148', '借', 'シャク', 'か.りる', 'shaku', 'kariru', 'Meminjam', '借金', 'しゃっきん', 'Utang'),
  ('N4', '149', '曜', 'ヨウ', '-', 'you', '-', 'Hari (dalam seminggu)', '曜日', 'ようび', 'Hari (dalam seminggu)'),
  ('N4', '150', '飲', 'イン', 'の.む', 'in', 'nomu', 'Minum', '飲み物', 'のみもの', 'Minuman'),
  ('N4', '151', '肉', 'ニク', '-', 'niku', '-', 'Daging', '牛肉', 'ぎゅうにく', 'Daging sapi'),
  ('N4', '152', '貸', 'タイ', 'か.す、かし', 'tai', 'kasu, kashi', 'Meminjamkan', '貸す', 'かす', 'Meminjamkan'),
  ('N4', '153', '堂', 'ドウ', '-', 'dou', '-', 'Aula, ruang publik', '食堂', 'しょくどう', 'Kantin/rumah makan'),
  ('N4', '154', '鳥', 'チョウ', 'とり', 'chou', 'tori', 'Burung', '小鳥', 'ことり', 'Burung kecil'),
  ('N4', '155', '飯', 'ハン', 'めし', 'han', 'meshi', 'Nasi, makanan', 'ご飯', 'ごはん', 'Nasi/makanan'),
  ('N4', '156', '勉', 'ベン', 'つと.める', 'ben', 'tsutomeru', 'Berusaha, rajin', '勤勉', 'きんべん', 'Rajin'),
  ('N4', '157', '冬', 'トウ', 'ふゆ', 'tou', 'fuyu', 'Musim dingin', '冬休み', 'ふゆやすみ', 'Libur musim dingin'),
  ('N4', '158', '昼', 'チュウ', 'ひる', 'chuu', 'hiru', 'Siang', '昼食', 'ちゅうしょく', 'Makan siang'),
  ('N4', '159', '茶', 'チャ、サ', '-', 'cha, sa', '-', 'Teh', 'お茶', 'おちゃ', 'Teh'),
  ('N4', '160', '弟', 'テイ、ダイ、デ', 'おとうと', 'tei, dai, de', 'otouto', 'Adik laki-laki', '兄弟', 'きょうだい', 'Saudara kandung'),
  ('N4', '161', '牛', 'ギュウ', 'うし', 'gyuu', 'ushi', 'Sapi', '牛乳', 'ぎゅうにゅう', 'Susu sapi'),
  ('N4', '162', '魚', 'ギョ', 'うお、さかな', 'gyo', 'uo, sakana', 'Ikan', '金魚', 'きんぎょ', 'Ikan mas koki'),
  ('N4', '163', '兄', 'キョウ、ケイ', 'あに', 'kyou, kei', 'ani', 'Kakak laki-laki', 'お兄さん', 'おにいさん', 'Kakak laki-laki (panggilan)'),
  ('N4', '164', '犬', 'ケン', 'いぬ', 'ken', 'inu', 'Anjing', '子犬', 'こいぬ', 'Anak anjing'),
  ('N4', '165', '妹', 'マイ', 'いもうと', 'mai', 'imouto', 'Adik perempuan', '姉妹', 'しまい', 'Kakak-adik perempuan'),
  ('N4', '166', '姉', 'シ', 'あね', 'shi', 'ane', 'Kakak perempuan', 'お姉さん', 'おねえさん', 'Kakak perempuan (panggilan)'),
  ('N4', '167', '漢', 'カン', '-', 'kan', '-', 'Tiongkok/China', '漢方', 'かんぽう', 'Obat tradisional Tiongkok');
